Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2018-11, with the labels that each got.

#175 Functions to get registered factors and variables in workspace
  src/IncrementalInference.jl
  src/SolverUtilities.jl
Labels: documentation, enhancement

#180 fast-forward NLsolver < v3.0.0
  REQUIRE
  src/FactorGraph01.jl
  src/IncrementalInference.jl
  src/SolverUtilities.jl
  test/runtests.jl
  test/testCommonConvWrapper.jl
  test/testMultithreaded.jl
  test/testNLsolve.jl
  test/testNumericRootGenericRandomized.jl
Labels: fast-forward

#181 add print graph max,
  src/FGOSUtils.jl
  src/IncrementalInference.jl
Labels: enhancement, utils

#176 helper functions to monitor tree during solve
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/SolveTree01.jl
  src/SolverUtilities.jl
  src/tmpimgs/readme
  test/testmultihypothesisapi.jl
Labels: documentation, enhancement, visualization

#191 change to Prior API in test
  test/testBayesTreeChordalProp.jl
  test/testBayesTreeiSAM2Example.jl
Labels: API
