Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2018-12, with the labels that each got.

#192 Bayes Net bug fix post 1.0 update, maintenance
  src/ApproxConv.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/SolveTree01.jl
  src/SolverUtilities.jl
Labels: bug, documentation, enhancement

#194 remove todo doc string instructions
  src/FactorGraph01.jl
  src/JunctionTree.jl
  src/SolveTree01.jl
Labels: documentation, upkeep

#193 This seems to be needed for proto deserialization, at least with CG
  src/DefaultNodeTypes.jl
Labels: bug, serialization

#196 nlsolve(.., inplace=true)
  REQUIRE
  src/SolverUtilities.jl
  test/testCommonConvWrapper.jl
  test/testNLsolve.jl
Labels: bug, deprecated, upstream

#177 start adding ccolamd work for manipulating variable ordering
  src/IncrementalInference.jl
  src/ccolamd.jl
Labels: enhancement, performance

#197 Bugbug/cleanromedump
  src/DispatchPackedConversions.jl
  src/FGOSUtils.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  test/testExpandedJLD.jl
  test/testdata/compatibility_test_fg.jld2
  test/testgraphpackingconverters.jl
Labels: bug, enhancement, serialization, testing, workaround
