Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2018-08, with the labels that each got.

#119 Maintenance/latejuly18
  src/ApproxConv.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/SolveTree01.jl
  src/SolverUtilities.jl
  test/testGenericWrapParam.jl
Labels: debug tools, enhancement

#120 some cleanup
  src/DispatchPackedConversions.jl
  src/deprecated.jl
Labels: deprecated, upkeep

#121 fix issue #118
  src/FactorGraph01.jl
Labels: enhancement, feature request

#127 Feature/multithreadingminimize
  src/ApproxConv.jl
  src/DispatchPackedConversions.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/SolverUtilities.jl
  src/deprecated.jl
  test/testGenericWrapParam.jl
  test/testgraphpackingconverters.jl
  test/testmultihypothesisapi.jl
  test/testnullhypothesis.jl
Labels: bug, refactoring

#128 multithreaded convolutions are working
  src/ApproxConv.jl
  src/DispatchPackedConversions.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/SolverUtilities.jl
  test/runtests.jl
  test/testGenericWrapParam.jl
  test/testMultithreaded.jl
  test/testpartialconstraint.jl
Labels: enhancement, mutlithreading, refactoring

#129 Sample from general weight vectors
  REQUIRE
  src/AliasScalarSampling.jl
  src/ApproxConv.jl
  src/IncrementalInference.jl
  src/SolverUtilities.jl
  src/deprecated.jl
  test/testGenericWrapParam.jl
Labels: enhancement, needed downstream

#130 Feature/expandmultihypo
  src/ExplicitDiscreteMarginalizations.jl
  src/FGOSUtils.jl
  src/IncrementalInference.jl
  test/runtests.jl
  test/testExplicitMultihypo.jl
Labels: multihypothesis, testing

#131 Renormalize categorical probabilities when parsing multi hypothesis factors
  src/DispatchPackedConversions.jl
Labels: bug

#136 Feature/nodenaming
  src/FGOSUtils.jl
Labels: enhancement, needed downstream

#137 Feature/expandmultihypo
  src/ApproxConv.jl
  src/ExplicitDiscreteMarginalizations.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  test/testExplicitMultihypo.jl
Labels: multihypothesis, refactoring

#139 Maintenance/aug218improvements
  src/AliasScalarSampling.jl
  src/DefaultNodeTypes.jl
  src/DispatchPackedConversions.jl
  src/FGOSUtils.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
Labels: enhancement, needed downstream, refactoring, type relaxation

#138 tri-modal starting to work
  src/ApproxConv.jl
  test/testExplicitMultihypo.jl
  test/testmultihypothesisapi.jl
Labels: enhancement, multihypothesis, testing

#140 bugfix and approxConvBinary
  src/ApproxConv.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
Labels: bug, enhancement

#141 better sorting of ls for nested labels
  src/FGOSUtils.jl
  src/IncrementalInference.jl
  test/testExplicitMultihypo.jl
Labels: enhancement

#142 Improve testing remove some comments
  examples/IllustrateAutoInit.jl
  src/DispatchPackedConversions.jl
  src/FactorGraph01.jl
  src/JunctionTree.jl
  test/testlocalconstraintexamples.jl
Labels: API, testing, upkeep
