Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2018-10, with the labels that each got.

#111 starting Julia 0.7 testing fixes
  .travis.yml
  README.md
  REQUIRE
  examples/ApproximateConvolution.jl
  examples/IllustrateAutoInit.jl
  examples/squarefixedpoint.jl
  src/ApproxConv.jl
  src/DataLayerAPI.jl
  src/DefaultNodeTypes.jl
  src/DispatchPackedConversions.jl
  src/ExplicitDiscreteMarginalizations.jl
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/GraphConstraintTypes.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/SerializingDistributions.jl
  src/SolveTree01.jl
  src/SolverUtilities.jl
  src/TreePotentials01.jl
  src/ccolamd.jl
  src/deprecated.jl
  test/TestModuleFunctions.jl
  test/fourdoortest.jl
  test/runtests.jl
  test/saveconvertertypes.jl
  test/testBayesTreeiSAM2Example.jl
  test/testCommonConvWrapper.jl
  test/testExpandedJLD.jl
  test/testExplicitMultihypo.jl
  test/testFactorMetadata.jl
  test/testMultithreaded.jl
  test/testNumericRootGenericRandomized.jl
  test/testdata/compatibility_test_fg.jld
  test/testdata/compatibility_test_fg.jld2
  test/testgraphpackingconverters.jl
  test/testlocalconstraintexamples.jl
  test/testmultihypothesisapi.jl
  test/testnullhypothesis.jl
  test/testpartialconstraint.jl
  test/typeReturnMemRef.jl
Labels: upkeep

#167 remove warnings
  src/ApproxConv.jl
Labels: deprecated, needed downstream

#168 fix and remove more warnings
  examples/squarefixedpoint.jl
  src/DispatchPackedConversions.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/JunctionTree.jl
  src/SolveTree01.jl
  src/SolverUtilities.jl
  test/fourdoortest.jl
  test/testBayesTreeChordalProp.jl
Labels: testing

#169 small fix
  REQUIRE
  examples/ApproximateConvolution.jl
  src/FactorGraph01.jl
  src/IncrementalInference.jl
  src/SolveTree01.jl
Labels: deprecated, example

#170 fix for fixed lag operation
  src/SolverUtilities.jl
Labels: bug

#171 old changes
  src/FactorGraph01.jl
  src/IncrementalInference.jl
Labels: enhancement

#172 Feature/multilangzmq
  src/FGOSUtils.jl
  src/IncrementalInference.jl
  src/SerializingDistributions.jl
Labels: enhancement, needed downstream
