Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2018-09, with the labels that each got.

#144 Fixed lag is starting to work
  src/DispatchPackedConversions.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/SolveTree01.jl
  src/SolverUtilities.jl
Labels: enhancement, fixed lag

#146 set ThreadingModel over factor graph
  src/FGOSUtils.jl
  src/IncrementalInference.jl
Labels: enhancement, mutlithreading

#149 SingleThreaded default with setThreadsAll fix
  src/FGOSUtils.jl
  src/FactorGraph01.jl
Labels: bug, mutlithreading

#150 Better JLD support, and solve, testing
  examples/IllustrateAutoInit.jl
  src/DefaultNodeTypes.jl
  src/DispatchPackedConversions.jl
  src/FactorGraph01.jl
  src/IncrementalInference.jl
  src/SerializingDistributions.jl
  test/runtests.jl
  test/testExpandedJLD.jl
  test/testExplicitMultihypo.jl
  test/testFactorMetadata.jl
  test/testMultithreaded.jl
  test/testdata/compatibility_test_fg.jld
Labels: enhancement, jld, testing

#151 added argument to choose graphviz layout engine
  src/FactorGraph01.jl
Labels: enhancement

#152 Feature/fixjldloadsolve
  src/ApproxConv.jl
  src/DispatchPackedConversions.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
Labels: bug, jld

#153 Feature/fixedlag01
  src/DispatchPackedConversions.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/SolveTree01.jl
  src/SolverUtilities.jl
  test/testExpandedJLD.jl
  test/testdata/compatibility_test_fg.jld
Labels: API, enhancement, jld, testing

#154 don't save jld
  test/testExpandedJLD.jl
Labels: bug, jld

#155 add fastnorm function
  src/IncrementalInference.jl
  src/SolverUtilities.jl
Labels: enhancement

#156 oops fastnorm fix
  src/ApproxConv.jl
  src/FactorGraph01.jl
  src/SolverUtilities.jl
Labels: bug

#158 add keyword N to batchSolve!
  src/SolverUtilities.jl
Labels: enhancement

#160 ability to supress most printouts
  src/FactorGraph01.jl
  src/JunctionTree.jl
  src/SolveTree01.jl
Labels: enhancement, logging, print

#161 Hotfix/batchsolve n
  src/FactorGraph01.jl
  src/SolverUtilities.jl
Labels: enhancement

#163 Dbfactors, common decoding code
  src/DispatchPackedConversions.jl
Labels: bug, serialization

#159 different weight normalization
  src/AliasScalarSampling.jl
Labels: bug
