Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2019-06, with the labels that each got.

#286 Feature/dfgintegration
  .travis.yml
  Manifest.toml
  Project.toml
  REQUIRE
  src/ApproxConv.jl
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/DefaultNodeTypes.jl
  src/Deprecated.jl
  src/DispatchPackedConversions.jl
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/SolveTree01.jl
  src/SolverUtilities.jl
  src/SubGraphFunctions.jl
  src/TreeBasedInitialization.jl
  src/serialization/models/distributions.jl
  src/serialization/models/factors.jl
  src/serialization/services/distributions.jl
  test/basicGraphsOperations.jl
  test/fourdoortest.jl
  test/runtests.jl
  test/serialization.jl
  test/testgraphpackingconverters.jl
  test/unittests/FactorGraph01_tests.jl
Labels: dfg, refactoring

#305 minor fixes to functions
  src/FactorGraph01.jl
Labels: bug fix, dfg

#306 removing require file
  REQUIRE
Labels: deprecated, toml

#308 Tomls/2019 q2/update
  Manifest.toml
  Project.toml
  examples/ApproximateConvolution.jl
  examples/IllustrateAutoInit.jl
  examples/RobotFourDoor.jl
  examples/squarefixedpoint.jl
  src/ApproxConv.jl
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/SolveTree01.jl
  test/fourdoortest.jl
  test/testBayesTreeChordalProp.jl
  test/testBayesTreeiSAM2Example.jl
  test/testCommonConvWrapper.jl
  test/testCompareVariablesFactors.jl
  test/testExpandedJLD.jl
  test/testFactorMetadata.jl
  test/testMultithreaded.jl
  test/testgraphpackingconverters.jl
  test/testlocalconstraintexamples.jl
  test/testmultihypothesisapi.jl
  test/testnullhypothesis.jl
  test/testpartialconstraint.jl
Labels: dependencies, dfg, toml

#309 Partial fix testing, JLD2 bypassed for now
  .travis.yml
  Manifest.toml
  Project.toml
  src/DispatchPackedConversions.jl
  src/FGOSUtils.jl
  test/runtests.jl
  test/serialization.jl
  test/testCompareVariablesFactors.jl
Labels: dfg, jld, needs testing, regression, testing, upstream

#311 Moving from Caesar to IIF
  src/DispatchPackedConversions.jl
  src/IncrementalInference.jl
Labels: enhancement

#310 fix rome tests on partials
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/SolveTree01.jl
  src/SolverUtilities.jl
  test/testgraphpackingconverters.jl
  test/testpartialconstraint.jl
Labels: API, dfg, needed downstream, testing

#313 update tomls
  Manifest.toml
  Project.toml
Labels: compat, dependencies, toml

#314 some refactoring and cleanup
  src/FactorGraph01.jl
  src/IncrementalInference.jl
Labels: maintenance

#315 add downsolve to clique state machine
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/Deprecated.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/SolveTree01.jl
  src/SolverUtilities.jl
  src/TreeBasedInitialization.jl
  test/testpartialconstraint.jl
Labels: clique state machine, inference, refactoring

#317 add solve tree debug option for Task access
  src/IncrementalInference.jl
  src/SolveTree01.jl
Labels: clique state machine, debug tools, inference

#323 Cliqsm/recyclecliqs
  Manifest.toml
  Project.toml
  src/CliqStateMachine.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/SolveTree01.jl
  src/SolverUtilities.jl
  src/TreeBasedInitialization.jl
  test/unittests/FactorGraph01_tests.jl
Labels: clique state machine, inference, recycle cliques

#320 Updates to IIF for CloudGraphs DFG driver
  Manifest.toml
  Project.toml
  src/CliqStateMachine.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/SolveTree01.jl
  src/SolverUtilities.jl
  test/testgraphpackingconverters.jl
Labels: breaking changes, dfg, graph management, serialization

#324 Updating API call for new signatures
  Manifest.toml
  Project.toml
  src/JunctionTree.jl
Labels: API, breaking changes, dfg

#326 restore fixed lag on solveTree!
  src/FactorGraph01.jl
  src/SolverUtilities.jl
Labels: API, fixed lag, inference

#329 missing export
  src/IncrementalInference.jl
  src/JunctionTree.jl
Labels: API, upstream

#331 update fourdoor test for solveTree!
  test/fourdoortest.jl
Labels: API, testing

#333 fix getfnctype bug
  src/FactorGraph01.jl
Labels: bug fix

#334 fix auto init of clique cycle order
  src/FactorGraph01.jl
  src/TreeBasedInitialization.jl
Labels: autoinit, bug fix, inference

#336 getTreeAllFrontalSyms needs dfg
  src/CliqStateMachineUtils.jl
  src/JunctionTree.jl
  src/SolveTree01.jl
Labels: API, bug fix
