Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2019-09, with the labels that each got.

#379 Add julia 1.3 to travis
  .travis.yml
Labels: travis

#378 down msg priors, update tree construction, and logpath
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/CompareUtils.jl
  src/DefaultNodeTypes.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/SolveTree01.jl
  src/SolverAPI.jl
  src/TreeBasedInitialization.jl
  test/testCompareVariablesFactors.jl
  test/testJunctionTree2.jl
Labels: bayes junction tree, debug tools, enhancement, inference, refactoring

#377 WIP: maintenance updates and enhancements
  src/BeliefTypes.jl
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/CompareUtils.jl
  src/DefaultNodeTypes.jl
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/InferDimensionUtils.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/SolveTree01.jl
  src/SolverAPI.jl
  src/TreeBasedInitialization.jl
  test/testCompareVariablesFactors.jl
  test/testJunctionTree2.jl
  test/testMultiHypo2Door.jl
Labels: clique state machine, testing

#386 Maintenance cleanup and treeinit prep
  examples/IllustrateAutoInit.jl
  examples/squarefixedpoint.jl
  src/AdditionalUtils.jl
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/Deprecated.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/SolveTree01.jl
  src/TreeBasedInitialization.jl
Labels: bayes junction tree, inference

#388 down solve with frontal neighbors,
  src/AdditionalUtils.jl
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/SolveTree01.jl
  src/SubGraphFunctions.jl
  src/TreeBasedInitialization.jl
Labels: autoinit, clique state machine, inference

#389 update docs and dfg compat
  Project.toml
  src/AliasScalarSampling.jl
Labels: compat, dfg, documentation

#391 manual init with points
  src/FactorGraph01.jl
Labels: API, enhancement

#392 limit fixed down solve option
  src/CliqStateMachineUtils.jl
  src/FGOSUtils.jl
  src/FactorGraphTypes.jl
Labels: bug fix, clique state machine, enhancement, fixed lag, inference

#394 lift lower compat on kde
  Project.toml
Labels: compat, inference, upstream

#397 small fixes here and there
  src/Deprecated.jl
  test/testCompareVariablesFactors.jl
Labels: maintenance

#400 add Sphere1 and fix tests
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/Factors/Sphere1D.jl
  src/IncrementalInference.jl
  src/Variables/Sphere1D.jl
  test/testBayesTreeiSAM2Example.jl
Labels: enhancement, testing

#401 fixes and maintenance
  src/AdditionalUtils.jl
  src/IncrementalInference.jl
  src/SolveTree01.jl
  src/SolverUtilities.jl
Labels: maintenance

#380 LightGraphDFG was renamed to MetaGraphDFG
  Project.toml
  src/JunctionTreeTypes.jl
Labels: dfg, upstream
