Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2019-11, with the labels that each got.

#425 various fixes and improvements
  src/AdditionalUtils.jl
  src/ApproxConv.jl
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/IncrementalInference.jl
  src/InferDimensionUtils.jl
  src/JunctionTree.jl
  src/SolveTree01.jl
  src/TreeBasedInitialization.jl
Labels: enhancement

#428 factor mean calculations and getVariablePPE
  src/ApproxConv.jl
  src/FGOSUtils.jl
  src/IncrementalInference.jl
  src/SolveTree01.jl
Labels: API, enhancement, maintenance, parametric estimates

#429 fix 427 init with multihypo
  src/ApproxConv.jl
  src/ExplicitDiscreteMarginalizations.jl
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/IncrementalInference.jl
  test/TestCSMMultihypo.jl
  test/runtests.jl
  test/testmultihypothesisapi.jl
Labels: autoinit, inference, multihypothesis

#431 Update CliqStateMachine.jl
  src/CliqStateMachine.jl
Labels: bug fix, clique state machine

#412 Remove SymbolDFG and MetaGraphsDFG before DFG v0.5.0
  src/JunctionTreeTypes.jl
Labels: refactoring, upstream

#417 Changes for DFG 0.5
  Project.toml
  src/CompareUtils.jl
  src/IncrementalInference.jl
  src/JunctionTreeTypes.jl
Labels: dfg, refactoring, upstream

#434 Fix for tests - note that having different estimates will fail in compare
  test/testCompareVariablesFactors.jl
Labels: testing

#435 Moving compare factor data to DFG
  src/DispatchPackedConversions.jl
Labels: refactoring, upstream

#421 Feature/update variable estimates
  Project.toml
  src/CliqStateMachineUtils.jl
  src/DispatchPackedConversions.jl
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  test/testCompareVariablesFactors.jl
Labels: feature request, needs testing, upstream

#437 update square root example
  examples/FixedPointIllustrationsSquare.jl
  examples/SquareRootTypes.jl
  examples/squarefixedpoint.jl
Labels: example

#440 general cleanup and few new functions
  src/CliqStateMachine.jl
  src/FGOSUtils.jl
  src/IncrementalInference.jl
  src/SolveTree01.jl
Labels: enhancement, maintenance

#444 fix warning DFG v0.5.0
  src/ApproxConv.jl
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/IncrementalInference.jl
Labels: API, deprecated, dfg, maintenance, standardization, upstream

#445 fix dep warn on hasVariable
  src/TreeBasedInitialization.jl
  test/basicGraphsOperations.jl
Labels: API, deprecated, dfg, upstream

#449 Twig/4 q19/solvable
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/FactorGraph01.jl
  src/JunctionTree.jl
  src/SubGraphFunctions.jl
Labels: enhancement

#452 Functions moved to DFG
  src/FGOSUtils.jl
  src/IncrementalInference.jl
Labels: dfg, graph management, inference

#450 introduce real time tether
  Project.toml
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/SubGraphFunctions.jl
Labels: graph management, inference, real time tether

#453 drop hasFactor for exists
  src/IncrementalInference.jl
  src/TreeBasedInitialization.jl
Labels: deprecated, dfg, upstream

#454 add tether utils
  src/IncrementalInference.jl
  src/TetherUtils.jl
Labels: inference, needed downstream, real time tether, refactoring, utils

#457 add deprecation warning
  src/FactorGraphTypes.jl
Labels: maintenance
