Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2019-10, with the labels that each got.

#399 Cherrypick sparse getEliminationOrder and const InMemDFGType
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/FactorGraph01.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/SubGraphFunctions.jl
Labels: performance

#395 Feature/3Q19/addingppe
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/SubGraphFunctions.jl
  test/runtests.jl
Labels: inference, parametric estimates

#408 add approxConvCircular
  src/AdditionalUtils.jl
  src/IncrementalInference.jl
Labels: enhancement

#411 add solveFactorMeasurements
  src/IncrementalInference.jl
  src/SolverUtilities.jl
Labels: enhancement, inference

#410 remove a few duplicate functions moved to DFG
  src/ApproxConv.jl
  src/CompareUtils.jl
  src/Deprecated.jl
  src/DispatchPackedConversions.jl
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/InferDimensionUtils.jl
  src/JunctionTree.jl
  src/SolveTree01.jl
  src/SolverUtilities.jl
  src/SubGraphFunctions.jl
  src/TreeBasedInitialization.jl
  test/testExpandedJLD.jl
  test/testFactorMetadata.jl
  test/testgraphpackingconverters.jl
  test/testmultihypothesisapi.jl
  test/unittests/FactorGraph01_tests.jl
Labels: dfg, maintenance, refactoring, upstream

#414 upper bound compat
  Project.toml
Labels: compat, registry, toml

#415 more compat
  Project.toml
Labels: compat, registry, toml

#418 Add generateTexTree function to produce Bayes tree with Tex labels.
  examples/TexTreeIllustration.jl
  src/JunctionTree.jl
Labels: enhancement, experimental

#419 add tests for generateTexTree
  .gitignore
  .travis.yml
  src/JunctionTree.jl
  test/runtests.jl
  test/testTexTreeIllustration.jl
  test/tmp/.gitkeep
Labels: needs documentation, testing, travis

#422 adding arm tests
  .travis.yml
Labels: multiarchitecture, testing, travis

#387 updates for cloud solve
  src/JunctionTree.jl
Labels: dfg, experimental
