Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2019-08, with the labels that each got.

#359 updates and fixes
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/SolveTree01.jl
  src/SolverAPI.jl
  test/unittests/FactorGraph01_tests.jl
Labels: clique state machine, inference

#361 treeproduct be dfg
  src/SolveTree01.jl
Labels: bug fix, dfg, upstream

#362 prep tag v0.7.4
  Manifest.toml
  src/IncrementalInference.jl
  src/SolveTree01.jl
Labels: API, bug fix, toml

#366 prevent bss sampler from letting NaN through
  src/AliasScalarSampling.jl
Labels: bug fix, corner case, enhancement, inference

#369 LightGraphs(MetaGraphs) option as cliq sub fg
  .gitignore
  Manifest.toml
  Project.toml
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/FactorGraphTypes.jl
  src/JunctionTreeTypes.jl
  src/SubGraphFunctions.jl
Labels: dfg, enhancement

#367 Fixes for abstraction
  src/JunctionTreeTypes.jl
Labels: clique state machine, dfg, performance

#374 refactor fgos to dfg, fix bss,
  Project.toml
  src/AliasScalarSampling.jl
  src/CompareUtils.jl
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/IncrementalInference.jl
Labels: bug fix, dependencies, refactoring, upstream

#376 maintenance and cleanup
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/SolveTree01.jl
  src/TreeBasedInitialization.jl
Labels: refactoring
