Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2019-01, with the labels that each got.

#199 Bug/softtypedeserialization
  src/DispatchPackedConversions.jl
  src/FGOSUtils.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/SolveTree01.jl
  test/testExpandedJLD.jl
  test/testdata/compatibility_test_fg.jld2
  test/testgraphpackingconverters.jl
Labels: enhancement, serialization, testing

#200 ensure global var and min initvals
  src/FactorGraph01.jl
  src/IncrementalInference.jl
Labels: enhancement, performance

#203 initval in VND is obsolete
  src/FactorGraph01.jl
Labels: deprecated, performance
