Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2020-11, with the labels that each got.

#1014 default to params.N
  src/CliqueStateMachine.jl
  src/FactorGraph.jl
Labels: enhancement, maintenance, parameters, standardization

#1018 add docs to Mixture
  src/Factors/Mixture.jl
Labels: documentation

#1017 User path in drawTree with spyCliqMat
  src/JunctionTree.jl
Labels: bayes junction tree, bug fix, visualization

#1021 new approxConv for chain of elements
  Project.toml
  src/ApproxConv.jl
  src/Deprecated.jl
  src/IncrementalInference.jl
  src/TetherUtils.jl
  test/priorusetest.jl
  test/runtests.jl
  test/testApproxConv.jl
  test/testBasicRecycling.jl
  test/testlocalconstraintexamples.jl
  test/testmultihypothesisapi.jl
  test/testpartialconstraint.jl
Labels: debug tools, enhancement

#1023 deprecate setCliqueDrawColor!
  attic/CSMCommon_Consolidate.jl
  attic/CSM_SiblDwnInit_fetch.jl
  attic/CliqueStateMachine_fetch.jl
  src/CliqStateMachineUtils.jl
  src/CliqueStateMachine.jl
  src/Deprecated.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/ParametricCSMFunctions.jl
  src/SolverUtilities.jl
  src/TreeMessageUtils.jl
Labels: API, clique state machine, deprecation, maintenance

#1022 Removing bayes net draw while deprecating older Graphs.jl
  src/JunctionTree.jl
Labels: API, bayes net, deprecation, maintenance

#1024 new test for fmd bug on multihypo
  src/Deprecated.jl
  src/IncrementalInference.jl
  src/NumericalCalculations.jl
  src/SolverUtilities.jl
  test/runtests.jl
  test/testMultihypoFMD.jl
Labels: bug, multihypothesis, sampling, testing

#1019 more fixes, and docs
  src/FactorGraph.jl
Labels: documentation, maintenance

#1020 initial ODERelative
  Project.toml
  src/ApproxConv.jl
  src/CliqStateMachineUtils.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/Factors/LinearRelative.jl
  src/IncrementalInference.jl
  src/InferDimensionUtils.jl
  src/ODE/ODERelative.jl
  src/SolverUtilities.jl
  src/TetherUtils.jl
  test/runtests.jl
  test/testApproxConv.jl
  test/testBasicRecycling.jl
  test/testODERelative.jl
Labels: factors, feature request, types
