Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2020-08, with the labels that each got.

#814 deconv msg likelihoods option
  src/BeliefTypes.jl
  src/CliqStateMachine.jl
  src/CliqStateMachine_Parametric.jl
  src/DeconvUtils.jl
  src/FGOSUtils.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/TreeMessageUtils.jl
  test/testDefaultDeconv.jl
Labels: inference, types

#815 v0.14.2-rc1
  Project.toml
  src/BeliefTypes.jl
  src/CliqStateMachine.jl
  src/CliqStateMachine_Parametric.jl
  src/DeconvUtils.jl
  src/FGOSUtils.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/TreeMessageUtils.jl
  test/testDefaultDeconv.jl
Labels: release

#817 add listTypeTree
  Project.toml
  src/FGOSUtils.jl
  src/IncrementalInference.jl
  src/RequireInteractiveUtils.jl
Labels: dependencies, enhancement, types, user experience

#813 Updates towards stateless softtypes
  src/CanonicalGraphExamples.jl
  src/DefaultNodeTypes.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  test/testpartialconstraint.jl
Labels: bug fix, deprecation, softtype

#818 drop old deprecations
  examples/ApproximateConvolution.jl
  examples/FixedPointIllustrationsSquare.jl
  examples/MultiHypo3Door.jl
  examples/squarefixedpoint.jl
  src/AdditionalUtils.jl
  src/CliqStateMachineUtils.jl
  src/CliqStateMachine_Parametric.jl
  src/Deprecated.jl
  src/FactorGraph.jl
  src/JunctionTree.jl
  src/SolveTree.jl
  src/SolveTree_Parametric.jl
  src/SubGraphFunctions.jl
  src/TreeBasedInitialization.jl
  src/TreeMessageAccessors.jl
  src/TreeMessageUtils.jl
  test/testBasicCSM.jl
  test/testBasicForwardConvolve.jl
  test/testCliqueFactors.jl
  test/testCommonConvWrapper.jl
  test/testJunctionTreeConstruction.jl
  test/testMultimodal1D.jl
  test/testProductReproducable.jl
  test/testSolveOrphanedFG.jl
  test/testTreeSaveLoad.jl
  test/testlocalconstraintexamples.jl
  test/testmultihypothesisapi.jl
  test/testpartialconstraint.jl
Labels: deprecation, maintenance

#821 fix deprecations
  examples/BayesTreeIllustration.jl
  src/CliqStateMachineUtils.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/SolveTree.jl
  test/unittests/FactorGraph01_tests.jl
Labels: API, deprecation, maintenance

#820 update LinearConditional
  src/DeconvUtils.jl
  src/DefaultNodeTypes.jl
  src/FactorGraphTypes.jl
  src/TreeMessageUtils.jl
Labels: enhancement, factors, types

#824 _evalType still needed for zmq
  src/Deprecated.jl
Labels: deprecation, needed downstream

#823 Populate full variable and use ns time
  src/ApproxConv.jl
  src/FactorGraph.jl
Labels: softtype, timestamps

#826 FF DFG upstream integration test branch
  Project.toml
  README.md
  examples/ApproximateConvolution.jl
  examples/BayesTreeIllustration.jl
  examples/FixedPointIllustrationsSquare.jl
  examples/MultiHypo3Door.jl
  examples/squarefixedpoint.jl
  src/AdditionalUtils.jl
  src/ApproxConv.jl
  src/BeliefTypes.jl
  src/CanonicalGraphExamples.jl
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/CliqStateMachine_Parametric.jl
  src/DeconvUtils.jl
  src/DefaultNodeTypes.jl
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/InferDimensionUtils.jl
  src/JunctionTree.jl
  src/ParametricUtils.jl
  src/RequireInteractiveUtils.jl
  src/SolveTree.jl
  src/SolveTree_Parametric.jl
  src/SubGraphFunctions.jl
  src/TreeBasedInitialization.jl
  src/TreeMessageAccessors.jl
  src/TreeMessageUtils.jl
  src/Variables/Sphere1D.jl
  test/testBasicCSM.jl
  test/testBasicForwardConvolve.jl
  test/testCliqueFactors.jl
  test/testCommonConvWrapper.jl
  test/testDefaultDeconv.jl
  test/testJunctionTreeConstruction.jl
  test/testMultimodal1D.jl
  test/testProductReproducable.jl
  test/testSolveOrphanedFG.jl
  test/testTreeSaveLoad.jl
  test/testlocalconstraintexamples.jl
  test/testmultihypothesisapi.jl
  test/testpartialconstraint.jl
  test/unittests/FactorGraph01_tests.jl
Labels: testing, upstream

#829 fix deprecations dfg v0.10
  src/Deprecated.jl
  src/FactorGraph.jl
  src/IncrementalInference.jl
  test/TestModuleFunctions.jl
Labels: deprecation, dfg, maintenance

#828 Cleanup for DFG v.10.0
  src/Deprecated.jl
Labels: deprecation, maintenance, null hypothesis, standardization, upstream

#831 loadDFG, deconvSolvekey, and mmd
  src/CliqStateMachineUtils.jl
  src/DeconvUtils.jl
  src/FGOSUtils.jl
  src/IncrementalInference.jl
Labels: deconvolution, dfg, enhancement, feature request, upstream, user experience

#832 clean up addVariable!
  src/DeconvUtils.jl
  src/DispatchPackedConversions.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/IncrementalInference.jl
  src/RequireInteractiveUtils.jl
  test/testMultimodal1D.jl
Labels: API, breaking changes, deprecation, enhancement, graph management, maintenance, standardization

#834 compat DFG v0.10
  Project.toml
Labels: compat, dependencies, dfg, toml

#835 fast forward
  Project.toml
  src/CliqStateMachineUtils.jl
  src/DeconvUtils.jl
  src/DispatchPackedConversions.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/IncrementalInference.jl
  src/RequireInteractiveUtils.jl
  test/testMultimodal1D.jl
Labels: dfg, testing, upstream

#836 some cleanup for v0.15
  Project.toml
  src/DeconvUtils.jl
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/IncrementalInference.jl
Labels: compat, maintenance

#822 update cholesky and bump v0.15.0
  Project.toml
  src/FactorGraph.jl
Labels: compat, deprecation, dfg, toml, variable ordering

#840 Put back softtype (variableType) deprecations simplify addVariable!
  src/FactorGraph.jl
Labels: deprecation, regression, softtype

#845 fix revise Gadfly utils separate file
  Project.toml
  src/EmbeddedPlottingUtils.jl
  src/IncrementalInference.jl
Labels: debug tools, maintenance, versioning, visualization

#846 v0.15.1-rc1
  Project.toml
  README.md
  src/EmbeddedPlottingUtils.jl
  src/IncrementalInference.jl
Labels: release

#856 bug fix regex storeOld
  src/SolverAPI.jl
Labels: bug fix, debug tools, super-solve

#858 Quiet buildSubraph with orphans
  src/CliqStateMachine.jl
  src/TreeBasedInitialization.jl
Labels: maintenance

#859 solveKey and PPE cleanup and mmd
  src/AnalysisTools.jl
  src/ApproxConv.jl
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/IncrementalInference.jl
  src/SolveTree.jl
  test/testBasicGraphs.jl
Labels: PPE, graph management, maintenance, needed downstream, standardization, visualization

#860 Tree building use @debug
  src/FactorGraph.jl
  src/JunctionTree.jl
Labels: bayes junction tree, debug tools, maintenance

#854 wip 2 on dwn msg consolidation
  src/BeliefTypes.jl
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/Deprecated.jl
  src/IncrementalInference.jl
  src/TreeBasedInitialization.jl
  src/TreeMessageUtils.jl
  src/TreeMsgDwnConsolidation.jl
  test/testnullhypothesis.jl
Labels: autoinit, clique state machine, deprecation, standardization

#862 fix rebuildFactorMetadata!
  src/DispatchPackedConversions.jl
  src/FactorGraph.jl
  test/testSaveLoadDFG.jl
Labels: bug fix, serialization

#864 remove misleading comment
  src/TreeBasedInitialization.jl
Labels: graph management

#861 WIP 3 consolidate dwnMsg
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/Deprecated.jl
  src/TreeBasedInitialization.jl
  src/TreeMessageUtils.jl
  src/TreeMsgDwnConsolidation.jl
  test/testBasicTreeInit.jl
Labels: clique state machine, deprecation, maintenance, refactoring

#866 add limititercliqs to solve
  src/SolveTree.jl
  src/SolverAPI.jl
Labels: clique state machine, debug tools, enhancement, feature request

#868 bug fixes
  src/IncrementalInference.jl
  src/SolveTree.jl
  test/testBasicTreeInit.jl
Labels: API, bug fix, debug tools, dfg, testing

#857 Parametric "take! and store" message again
  src/CliqStateMachine_Parametric.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/SolveTree_Parametric.jl
  src/SolverAPI.jl
  test/testBasicParametric.jl
Labels: bayes junction tree, bug fix, parametric solve, regression, stalemate

#871 warn_if_absent=false on update_!
  Project.toml
  src/CliqStateMachine.jl
  src/FactorGraph.jl
  src/SubGraphFunctions.jl
  test/testBasicCSM.jl
Labels: maintenance, user experience
