Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2020-04, with the labels that each got.

#665 fix #624, #83, add #236
  src/ApproxConv.jl
  src/CliqStateMachineUtils.jl
  src/FactorGraphTypes.jl
  src/SolveTree01.jl
  src/SolverAPI.jl
  test/runtests.jl
  test/testExplicitMultihypo.jl
  test/testMultiHypo2Door.jl
  test/testMultiprocess.jl
  test/testmultihypothesisapi.jl
Labels: bug fix, multihypothesis, null hypothesis, testing

#666 simplify tree drawing
  src/CliqStateMachine.jl
  src/Deprecated.jl
  src/FactorGraphTypes.jl
  src/ParametricCliqStateMachine.jl
  src/SolverAPI.jl
  test/testmultihypothesisapi.jl
Labels: bayes junction tree, debug tools, enhancement, standardization, visualization

#667 add test from #462
  test/runtests.jl
  test/testExplicitMultihypo.jl
  test/testMultihypoAndChain.jl
  test/testmultihypothesisapi.jl
Labels: inference, multihypothesis, testing

#668 clear deprecations
  src/DefaultNodeTypes.jl
  src/Deprecated.jl
  src/FactorGraph.jl
  src/IncrementalInference.jl
  test/runtests.jl
Labels: deprecated, enhancement, maintenance

#669 v0.11.1-rc1
  .travis.yml
  Project.toml
  README.md
  src/ApproxConv.jl
  src/BeliefTypes.jl
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/DefaultNodeTypes.jl
  src/Deprecated.jl
  src/DispatchPackedConversions.jl
  src/ExplicitDiscreteMarginalizations.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/ParametricCliqStateMachine.jl
  src/SolveTree01.jl
  src/SolverAPI.jl
  src/SolverUtilities.jl
  src/TreeMessageUtils.jl
  test/runtests.jl
  test/testBasicGraphs.jl
  test/testExplicitMultihypo.jl
  test/testMultiHypo2Door.jl
  test/testMultihypoAndChain.jl
  test/testMultimodal1D.jl
  test/testMultiprocess.jl
  test/testmultihypothesisapi.jl
Labels: release

#670 fast forward upstream testing
  .travis.yml
  Project.toml
  README.md
  examples/TreeAnalysis.jl
  src/ApproxConv.jl
  src/BeliefTypes.jl
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/DefaultNodeTypes.jl
  src/Deprecated.jl
  src/DispatchPackedConversions.jl
  src/ExplicitDiscreteMarginalizations.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/ParametricCliqStateMachine.jl
  src/SolveTree01.jl
  src/SolverAPI.jl
  src/SolverUtilities.jl
  src/SubGraphFunctions.jl
  src/TreeMessageUtils.jl
  test/runtests.jl
  test/testBasicGraphs.jl
  test/testExplicitMultihypo.jl
  test/testMultiHypo2Door.jl
  test/testMultihypoAndChain.jl
  test/testMultimodal1D.jl
  test/testMultiprocess.jl
  test/testmultihypothesisapi.jl
Labels: dfg, fast-forward, testing, upstream

#672 drawtree in loop as standard
  src/CliqStateMachine.jl
  src/FGOSUtils.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/SolverAPI.jl
  test/testAnalysisTools.jl
  test/testMultihypoAndChain.jl
Labels: bayes junction tree, clique state machine, standardization

#677 WIP Parametric Tree solve updates
  Project.toml
  src/BeliefTypes.jl
  src/Deprecated.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/ParametricCliqStateMachine.jl
  src/ParametricMessageUtils.jl
  src/ParametricSolveTree.jl
  src/ParametricUtils.jl
  src/SubGraphFunctions.jl
  src/TreeMessageUtils.jl
Labels: bayes junction tree, parametric solve

#676 WIP consolidating msg channels (#459)
  src/BeliefTypes.jl
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/Deprecated.jl
  src/JunctionTreeTypes.jl
  src/ParametricCliqStateMachine.jl
  src/SolveTree01.jl
  src/TreeBasedInitialization.jl
  src/TreeMessageUtils.jl
  test/testMixturePrior.jl
Labels: clique state machine, enhancement, maintenance, refactoring, standardization

#679 Consolidate Subgraph functions (DFG #373)
  Project.toml
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/ParametricCliqStateMachine.jl
  src/SubGraphFunctions.jl
  test/testCliqueFactors.jl
  test/testCompareVariablesFactors.jl
Labels: maintenance

#682 subgraph cleanup, bugfix,
  src/SolveTree01.jl
  src/SubGraphFunctions.jl
Labels: bug fix, maintenance

#684 fast forward
  Project.toml
  src/BeliefTypes.jl
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/ParametricCliqStateMachine.jl
  src/ParametricMessageUtils.jl
  src/ParametricSolveTree.jl
  src/ParametricUtils.jl
  src/SolveTree01.jl
  src/SolverAPI.jl
  src/SubGraphFunctions.jl
  src/TreeBasedInitialization.jl
  src/TreeMessageUtils.jl
  test/testAnalysisTools.jl
  test/testCliqueFactors.jl
  test/testCompareVariablesFactors.jl
  test/testMixturePrior.jl
  test/testMultihypoAndChain.jl
Labels: dfg, testing

#683 v0.11.2-rc1
  Project.toml
  src/BeliefTypes.jl
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/ParametricCliqStateMachine.jl
  src/ParametricMessageUtils.jl
  src/ParametricSolveTree.jl
  src/ParametricUtils.jl
  src/SolveTree01.jl
  src/SolverAPI.jl
  src/SubGraphFunctions.jl
  src/TreeBasedInitialization.jl
  src/TreeMessageUtils.jl
  test/testAnalysisTools.jl
  test/testCliqueFactors.jl
  test/testCompareVariablesFactors.jl
  test/testMixturePrior.jl
  test/testMultihypoAndChain.jl
Labels: release

#688 Additional updates to persist the values on initialization
  src/FactorGraph.jl
Labels: bug fix, maintenance

#690 reset to init vals
  src/FactorGraph.jl
  src/IncrementalInference.jl
  test/testBasicGraphs.jl
Labels: autoinit, enhancement, super-solve, user experience
