Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2020-02, with the labels that each got.

#569 better error message on maxparallel
  src/FactorGraph01.jl
Labels: maintenance, user experience

#570 Update testBasicGraphs.jl
  test/testBasicGraphs.jl
Labels: testing

#572 fix getFactorDim return as Int
  src/CliqStateMachine.jl
  src/InferDimensionUtils.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/TreeBasedInitialization.jl
Labels: bayes junction tree, debug tools, enhancement, types

#571 maint and improvements
  src/ApproxConv.jl
  src/CliqStateMachine.jl
  src/IncrementalInference.jl
  src/SolveTree01.jl
  src/SolverUtilities.jl
  test/testProductReproducable.jl
Labels: enhancement, maintenance, testing

#583 fix some deprecate warnings for v0.6
  src/ApproxConv.jl
  src/CliqStateMachineUtils.jl
  src/Deprecated.jl
  src/DispatchPackedConversions.jl
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/InferDimensionUtils.jl
  src/JunctionTree.jl
  src/ParametricCliqStateMachine.jl
  src/ParametricMessageUtils.jl
  src/ParametricUtils.jl
  src/SolveTree01.jl
  src/SolverUtilities.jl
  src/SubGraphFunctions.jl
  src/TreeBasedInitialization.jl
  test/testBasicParametric.jl
  test/testCompareVariablesFactors.jl
  test/testFactorMetadata.jl
  test/testSolveSetPPE.jl
  test/testgraphpackingconverters.jl
  test/testmultihypothesisapi.jl
  test/unittests/FactorGraph01_tests.jl
Labels: maintenance

#585 v0.8.5-rc1
  .github/workflows/TagBot.yml
  Project.toml
  src/ApproxConv.jl
  src/BeliefTypes.jl
  src/CanonicalGraphExamples.jl
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/DefaultNodeTypes.jl
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/InferDimensionUtils.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/ParametricCliqStateMachine.jl
  src/ParametricMessageUtils.jl
  src/ParametricSolveTree.jl
  src/ParametricUtils.jl
  src/SolveTree01.jl
  src/SolverAPI.jl
  src/SolverUtilities.jl
  src/SubGraphFunctions.jl
  src/TetherUtils.jl
  src/TreeBasedInitialization.jl
  test/runtests.jl
  test/testBasicGraphs.jl
  test/testBasicParametric.jl
  test/testCompareVariablesFactors.jl
  test/testProductReproducable.jl
  test/testVariousNSolveSize.jl
  test/testpartialconstraint.jl
Labels: release

#584 switch LightDFG as default
  src/IncrementalInference.jl
Labels: API, deprecated, dfg, graph management, types

#587 remove labels 580
  src/DefaultNodeTypes.jl
  src/FactorGraph01.jl
  src/Variables/Sphere1D.jl
Labels: deprecated, types

#590 remove old deprecations
  src/Deprecated.jl
Labels: deprecated, maintenance

#591 only test arm64 on julia 1.3
  .travis.yml
Labels: travis

#588 Development updates for DFG v0.6
  .travis.yml
  Project.toml
  src/ApproxConv.jl
  src/CliqStateMachineUtils.jl
  src/DispatchPackedConversions.jl
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/InferDimensionUtils.jl
  src/JunctionTree.jl
  src/ParametricCliqStateMachine.jl
  src/ParametricMessageUtils.jl
  src/ParametricUtils.jl
  src/SolveTree01.jl
  src/SolverUtilities.jl
  src/SubGraphFunctions.jl
  src/TreeBasedInitialization.jl
  test/testBasicParametric.jl
  test/testCompareVariablesFactors.jl
  test/testFactorMetadata.jl
  test/testSolveSetPPE.jl
  test/testgraphpackingconverters.jl
  test/testmultihypothesisapi.jl
  test/unittests/FactorGraph01_tests.jl
Labels: deprecated, maintenance

#594 fast forward for DFG v0.6 integration testing
  .github/workflows/TagBot.yml
  .travis.yml
  Project.toml
  src/ApproxConv.jl
  src/BeliefTypes.jl
  src/CanonicalGraphExamples.jl
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/DefaultNodeTypes.jl
  src/Deprecated.jl
  src/DispatchPackedConversions.jl
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/InferDimensionUtils.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/ParametricCliqStateMachine.jl
  src/ParametricMessageUtils.jl
  src/ParametricSolveTree.jl
  src/ParametricUtils.jl
  src/SolveTree01.jl
  src/SolverAPI.jl
  src/SolverUtilities.jl
  src/SubGraphFunctions.jl
  src/TetherUtils.jl
  src/TreeBasedInitialization.jl
  src/Variables/Sphere1D.jl
  test/runtests.jl
  test/testBasicGraphs.jl
  test/testBasicParametric.jl
  test/testCompareVariablesFactors.jl
  test/testFactorMetadata.jl
  test/testProductReproducable.jl
  test/testSolveSetPPE.jl
  test/testVariousNSolveSize.jl
  test/testgraphpackingconverters.jl
  test/testmultihypothesisapi.jl
  test/testpartialconstraint.jl
  test/unittests/FactorGraph01_tests.jl
Labels: fast-forward, testing, upstream

#596 Update .travis.yml
  .travis.yml
Labels: testing, travis

#598 Test on DFG v0.6 tag
  .travis.yml
Labels: testing

#601 fixes #416
  src/ApproxConv.jl
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/ParametricCliqStateMachine.jl
  src/SolveTree01.jl
  src/SolverAPI.jl
  src/TreeBasedInitialization.jl
  test/testBasicGraphs.jl
  test/testCompareVariablesFactors.jl
  test/testJunctionTreeConstruction.jl
  test/testSolveOrphanedFG.jl
  test/testTreeSaveLoad.jl
  test/testpartialconstraint.jl
Labels: deprecated, maintenance, refactoring

#603 Factor <: Real and Abstracts
  examples/ApproximateConvolution.jl
  examples/IllustrateAutoInit.jl
  examples/SquareRootTypes.jl
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/DefaultNodeTypes.jl
  src/Factors/Sphere1D.jl
  src/GraphConstraintTypes.jl
  src/SolverUtilities.jl
  src/SubGraphFunctions.jl
  src/TreeBasedInitialization.jl
  test/testCommonConvWrapper.jl
  test/testNLsolve.jl
  test/testNumericRootGenericRandomized.jl
  test/testmultihypothesisapi.jl
  test/testpartialconstraint.jl
Labels: enhancement, maintenance, standardization

#610 standard to graphinit,
  Project.toml
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/JunctionTree.jl
  test/testJunctionTreeConstruction.jl
Labels: API, autoinit, enhancement

#611 gen fg should use graphinit
  examples/MultiHypo3Door.jl
  src/AdditionalUtils.jl
  src/CanonicalGraphExamples.jl
  src/FactorGraph.jl
  src/ParametricMessageUtils.jl
  src/TetherUtils.jl
  src/TreeBasedInitialization.jl
  test/basicGraphsOperations.jl
  test/testCliqueFactors.jl
  test/testProductReproducable.jl
  test/testnullhypothesis.jl
  test/testpartialconstraint.jl
  test/unittests/FactorGraph01_tests.jl
Labels: autoinit, debug tools, standardization, user experience

#613 fix and test MixturePrior,
  src/DefaultNodeTypes.jl
  test/runtests.jl
  test/testMixturePrior.jl
Labels: bug fix, maintenance, types
