Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2020-01, with the labels that each got.

#516 ex2 test from #458
  src/SolverUtilities.jl
  test/testCliqueFactors.jl
Labels: bug, testing

#520 add tree build time
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/SolverAPI.jl
Labels: bayes junction tree, bug fix, debug tools, enhancement, performance

#524 fixes #523 GraphsDFG -> InMemDFGTyp
  src/CliqStateMachineUtils.jl
  src/JunctionTreeTypes.jl
Labels: bug fix

#505 fast forward with new stuff from master
  .gitignore
  Project.toml
  README.md
  src/AdditionalUtils.jl
  src/CanonicalGraphExamples.jl
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/Deprecated.jl
  src/DispatchPackedConversions.jl
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/InferDimensionUtils.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/SolveTree01.jl
  src/SolverAPI.jl
  src/SolverUtilities.jl
  src/SubGraphFunctions.jl
  src/TreeBasedInitialization.jl
  test/priorusetest.jl
  test/runtests.jl
  test/testBasicGraphs.jl
  test/testCliqueFactors.jl
  test/testCompareVariablesFactors.jl
  test/testJunctionTree2.jl
  test/testJunctionTreeConstruction.jl
  test/testTreeSaveLoad.jl
  test/unittests/FactorGraph01_tests.jl
Labels: fast-forward

#526 adjust test tolernance
  test/testBasicGraphs.jl
Labels: testing

#528 WIP MetaBayesTree
  Project.toml
  src/AdditionalUtils.jl
  src/CanonicalGraphExamples.jl
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/Deprecated.jl
  src/DispatchPackedConversions.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/InferDimensionUtils.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/SolveTree01.jl
  src/SolverAPI.jl
  src/SolverUtilities.jl
  src/SubGraphFunctions.jl
  src/TreeBasedInitialization.jl
  test/runtests.jl
  test/testBayesTreeiSAM2Example.jl
Labels: bayes junction tree, deprecated, enhancement, refactoring

#536 drop Julia 1.1 testing to reduce load
  .travis.yml
Labels: testing, travis

#519 [TESTING] for orphaned FGs
  src/JunctionTree.jl
  src/SolveTree01.jl
  test/runtests.jl
  test/testSolveOrphanedFG.jl
Labels: bayes junction tree, clique state machine, enhancement, inference, testing, user experience

#537 bug fix for #530
  src/SolveTree01.jl
Labels: bug fix

#538 attempt to fix #527
  .travis.yml
  test/runtests.jl
Labels: bug fix, testing, travis

#543 updates and compat DocSExt min 0.8
  Project.toml
  src/JunctionTreeTypes.jl
Labels: compat, maintenance

#494 Initial extraction of analysis tools and fuctions for Bayes tree.
  examples/TreeAnalysis.jl
  src/AnalysisTools.jl
  src/IncrementalInference.jl
  test/runtests.jl
  test/testAnalysisTools.jl
Labels: bayes junction tree, variable ordering

#544 make ccolamd usable,
  Project.toml
  examples/TreeAnalysis.jl
  src/AnalysisTools.jl
  src/FactorGraph01.jl
  src/IncrementalInference.jl
  test/runtests.jl
  test/testCcolamdOrdering.jl
Labels: bayes junction tree, ccolamd, testing, variable ordering

#545 loadCanonicalFG_ -> generateCanonicalFG_
  examples/TreeAnalysis.jl
  src/AnalysisTools.jl
  src/CanonicalGraphExamples.jl
  test/testAnalysisTools.jl
  test/testCcolamdOrdering.jl
  test/testJunctionTreeConstruction.jl
  test/testTreeSaveLoad.jl
Labels: maintenance, refactoring, standardization, user experience

#546 fix #489 spyCliqMat
  src/IncrementalInference.jl
Labels: bug fix, visualization

#550 fix PPE set during solve
  Project.toml
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/FGOSUtils.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/SolveTree01.jl
  src/SubGraphFunctions.jl
  test/runtests.jl
  test/testBasicGraphs.jl
  test/testCompareVariablesFactors.jl
  test/testExpandedJLD.jl
  test/testSolveSetPPE.jl
Labels: PPE, bug fix, clique state machine, inference, regression

#547 v0.8.4-rc1
  .github/workflows/CompatHelper.yml
  .gitignore
  .travis.yml
  Project.toml
  README.md
  examples/TreeAnalysis.jl
  src/AdditionalUtils.jl
  src/AnalysisTools.jl
  src/CanonicalGraphExamples.jl
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/Deprecated.jl
  src/DispatchPackedConversions.jl
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/InferDimensionUtils.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/SolveTree01.jl
  src/SolverAPI.jl
  src/SolverUtilities.jl
  src/SubGraphFunctions.jl
  src/TreeBasedInitialization.jl
  test/runtests.jl
  test/testAnalysisTools.jl
  test/testBasicGraphs.jl
  test/testBayesTreeiSAM2Example.jl
  test/testCcolamdOrdering.jl
  test/testCliqueFactors.jl
  test/testCompareVariablesFactors.jl
  test/testExpandedJLD.jl
  test/testJunctionTreeConstruction.jl
  test/testSolveOrphanedFG.jl
  test/testSolveSetPPE.jl
  test/testTreeSaveLoad.jl
  test/unittests/FactorGraph01_tests.jl
Labels: DO NOT MERGE YET, release

#553 fast forward for DFG integration testing
  .github/workflows/CompatHelper.yml
  .gitignore
  .travis.yml
  Project.toml
  README.md
  examples/TreeAnalysis.jl
  src/AdditionalUtils.jl
  src/AnalysisTools.jl
  src/CanonicalGraphExamples.jl
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/Deprecated.jl
  src/DispatchPackedConversions.jl
  src/FGOSUtils.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/InferDimensionUtils.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/SolveTree01.jl
  src/SolverAPI.jl
  src/SolverUtilities.jl
  src/SubGraphFunctions.jl
  src/TreeBasedInitialization.jl
  test/runtests.jl
  test/testAnalysisTools.jl
  test/testBasicGraphs.jl
  test/testBayesTreeiSAM2Example.jl
  test/testCcolamdOrdering.jl
  test/testCliqueFactors.jl
  test/testCompareVariablesFactors.jl
  test/testExpandedJLD.jl
  test/testJunctionTreeConstruction.jl
  test/testSolveOrphanedFG.jl
  test/testSolveSetPPE.jl
  test/testTreeSaveLoad.jl
  test/unittests/FactorGraph01_tests.jl
Labels: dfg, fast-forward, testing, upstream

#468 WIP Linear parametric solution
  src/BeliefTypes.jl
  src/CanonicalGraphExamples.jl
  src/DefaultNodeTypes.jl
  src/FactorGraph01.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/ParametricCliqStateMachine.jl
  src/ParametricMessageUtils.jl
  src/ParametricSolveTree.jl
  src/ParametricUtils.jl
  src/SolverAPI.jl
  src/SubGraphFunctions.jl
  src/TetherUtils.jl
  src/TreeBasedInitialization.jl
  test/runtests.jl
  test/testBasicParametric.jl
Labels: parametric solve

#557 fix partial FunctorPairwiseMinimize
  src/ApproxConv.jl
  src/CliqStateMachineUtils.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/SolveTree01.jl
  src/SolverAPI.jl
  src/SolverUtilities.jl
  test/testpartialconstraint.jl
Labels: bug fix, enhancement, inference

#560 not get factor mean Z
  src/TetherUtils.jl
Labels: bug fix

#517 add test for N != 100
  src/FactorGraphTypes.jl
  test/runtests.jl
  test/testVariousNSolveSize.jl
Labels: bug, help wanted, testing

#556 [BUGFIX] Sub-graph regression
  src/CliqStateMachineUtils.jl
Labels: bug fix

#563 add SolvedCount,
  Project.toml
  src/CliqStateMachine.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  test/testCompareVariablesFactors.jl
Labels: breaking changes, compat, dfg, enhancement, toml, upstream

#566 adding helper for fixed lag
  src/FGOSUtils.jl
Labels: enhancement, fixed lag

#565 Switch to current function version to remove deprecated warning (setSolverData!)
  src/FactorGraph01.jl
Labels: API, dependencies, deprecated, dfg, maintenance
