Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2020-05, with the labels that each got.

#693 ff upstream integration test branch
  src/FactorGraph.jl
  src/IncrementalInference.jl
  test/testBasicGraphs.jl
Labels: testing, upstream

#694 refactor deprecate some packing,
  src/Deprecated.jl
  src/DispatchPackedConversions.jl
Labels: deprecated, dfg, refactoring, serialization

#695 Develop [ing something??]
  Project.toml
  src/DispatchPackedConversions.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/TreeBasedInitialization.jl
  test/testCompareVariablesFactors.jl
  test/testSaveLoadDFG.jl
Labels: dfg

#697 updates for DFG#440
  .travis.yml
  Project.toml
  src/ApproxConv.jl
  src/Deprecated.jl
  src/DispatchPackedConversions.jl
  src/FactorGraph.jl
  src/IncrementalInference.jl
Labels: maintenance

#696 rm converters for packed types
  src/Deprecated.jl
  src/DispatchPackedConversions.jl
Labels: deprecated, maintenance, serialization

#701 travis "MASTER AND TAGS" and "DEV MASTERS"
  .travis.yml
Labels: testing, travis

#700 Also dispatch on solverData type for rebuildFactorMetadata!
  src/DispatchPackedConversions.jl
  src/IncrementalInference.jl
Labels: maintenance, serialization

#703 switch to buildSubgraph
  src/CliqStateMachine.jl
  src/IncrementalInference.jl
  src/SubGraphFunctions.jl
  src/TreeBasedInitialization.jl
  test/testCompareVariablesFactors.jl
Labels: API, deprecated, maintenance

#704 Update to fit with DFG #459 fixes to buildSubgraph function
  src/CliqStateMachine.jl
  src/SubGraphFunctions.jl
  src/TreeBasedInitialization.jl
  test/testCompareVariablesFactors.jl
Labels: maintenance

#706 remove setSerializationModule! from IIF tests
  test/testgraphpackingconverters.jl
Labels: maintenance

#711 Update .travis.yml
  .travis.yml
Labels: travis

#709 standardize to use solverParams and not params
  src/CanonicalGraphExamples.jl
  src/CliqStateMachine.jl
  src/CliqStateMachineUtils.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/ParametricCliqStateMachine.jl
  src/ParametricUtils.jl
  src/SubGraphFunctions.jl
  test/testBasicParametric.jl
  test/testSaveLoadDFG.jl
  test/testgraphpackingconverters.jl
Labels: maintenance, standardization

#710 bug fixes
  src/ApproxConv.jl
  src/Deprecated.jl
  src/FactorGraph.jl
  src/IncrementalInference.jl
  src/SolverUtilities.jl
Labels: API, bug fix, maintenance

#715 accumulateFactorChain
  src/IncrementalInference.jl
  src/SolverUtilities.jl
Labels: enhancement

#717 maxparallel -> SolverParams.maxincidence,
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/JunctionTree.jl
  src/SolverAPI.jl
  test/runtests.jl
Labels: API, maintenance, types, user experience

#718 improve api of util
  src/SolverUtilities.jl
Labels: API, enhancement

#719 swap order solveFactorMeasure
  src/SolverUtilities.jl
Labels: API, standardization

#720 Update .travis.yml
  .travis.yml
Labels: travis, upstream
