Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2021-05, with the labels that each got.

#1240 Initial parametric max mixtures poc
  src/FactorGraph.jl
  src/ParametricUtils.jl
  test/runtests.jl
  test/testMixtureParametric.jl
Labels: max mixtures, mixture, parametric solve

#1248 towards beehive numerical tests
  NEWS.md
  src/Deprecated.jl
  src/IncrementalInference.jl
  src/NumericalCalculations.jl
  src/ParametricUtils.jl
  src/SolverUtilities.jl
  src/TetherUtils.jl
  test/testDeadReckoningTether.jl
Labels: API, deprecation, enhancement, maintenance

#1249 towards #1246
  src/ApproxConv.jl
  src/Deprecated.jl
  src/FactorGraph.jl
  src/NumericalCalculations.jl
  src/ParametricUtils.jl
  src/SolverUtilities.jl
  src/TetherUtils.jl
Labels: API, enhancement, maintenance, refactoring

#1252 updates for AbstractManifold
  NEWS.md
  Project.toml
  src/FGOSUtils.jl
  src/Factors/Circular.jl
  src/Factors/EuclidDistance.jl
  src/Factors/LinearRelative.jl
  src/IncrementalInference.jl
  src/ParametricUtils.jl
  src/SolverUtilities.jl
  src/Variables/Circular.jl
  src/Variables/DefaultVariables.jl
Labels: API, maintenance, manifolds, upstream

#1251 fast-forward integration testing
  NEWS.md
  Project.toml
  README.md
  src/ApproxConv.jl
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/Factors/Circular.jl
  src/Factors/EuclidDistance.jl
  src/Factors/LinearRelative.jl
  src/IncrementalInference.jl
  src/NumericalCalculations.jl
  src/ParametricUtils.jl
  src/SolverUtilities.jl
  src/TetherUtils.jl
  src/Variables/Circular.jl
  src/Variables/DefaultVariables.jl
  test/runtests.jl
  test/testDeadReckoningTether.jl
  test/testMixtureParametric.jl
Labels: dfg, fast-forward, testing, upstream

#1253 code cleanup
  src/FGOSUtils.jl
Labels: maintenance

#1254 TRy fix JULIA_PKG_SERVER=""
  .github/workflows/ci.yml
Labels: CI, enhancement

#1256 update compat 21Q2
  Project.toml
Labels: compat, dependencies

#1255 tag v0.24.1-rc1
  .github/workflows/ci.yml
  NEWS.md
  Project.toml
  README.md
  src/ApproxConv.jl
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/Factors/Circular.jl
  src/Factors/EuclidDistance.jl
  src/Factors/LinearRelative.jl
  src/IncrementalInference.jl
  src/NumericalCalculations.jl
  src/ParametricUtils.jl
  src/SolverUtilities.jl
  src/TetherUtils.jl
  src/Variables/Circular.jl
  src/Variables/DefaultVariables.jl
  test/runtests.jl
  test/testDeadReckoningTether.jl
  test/testMixtureParametric.jl
Labels: release

#1257 fast-forward integration test
  .github/workflows/ci.yml
  .travis.yml
  Project.toml
  src/FGOSUtils.jl
Labels: dfg, fast-forward, testing, upstream
