Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2021-07, with the labels that each got.

#1285 add HeatmapDensityRegular
  Project.toml
  src/BeliefTypes.jl
  src/Flux/entities.jl
  src/HeatmapSampler.jl
  src/IncrementalInference.jl
Labels: AliasingScalarSampler, enhancement, inference, sampling

#1286 add HeatmapDensityRegular
  Project.toml
  src/BeliefTypes.jl
  src/Flux/entities.jl
  src/HeatmapSampler.jl
  src/IncrementalInference.jl
  src/entities/OptionalDensities.jl
Labels: AliasingScalarSampler, back port, bug fix, enhancement, inference, needs testing, sampling

#1288 wip, Vector{P} proper
  Project.toml
  src/ApproxConv.jl
  src/BeliefTypes.jl
  src/CompareUtils.jl
  src/DeconvUtils.jl
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/Factors/LinearRelative.jl
  src/ParametricCSMFunctions.jl
  src/ParametricUtils.jl
  src/TreeMessageUtils.jl
  test/testBasicParametric.jl
  test/testDefaultDeconv.jl
  test/testMixtureLinearConditional.jl
Labels: enhancement, manifolds, refactoring

#1290 update addEntropyOnManifoldHack! add AbstractManifoldMinimize
  examples/dev/testManiFactors.jl
  src/ApproxConv.jl
  src/FactorGraph.jl
  src/Factors/GenericFunctions.jl
  src/IncrementalInference.jl
  src/NumericalCalculations.jl
Labels: enhancement, manifolds, refactoring, standardization, work in progress

#1294 fix null hypo partials, and test
  Project.toml
  src/ApproxConv.jl
  test/runtests.jl
  test/testPartialNH.jl
Labels: bug fix, inference, null hypothesis, partials, testing

#1292 WIP on manifold optimization and factors
  examples/dev/factors_sandbox.jl
  examples/dev/testManiFactors.jl
  src/ApproxConv.jl
  src/CompareUtils.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/Factors/GenericFunctions.jl
  src/NumericalCalculations.jl
  src/ParametricUtils.jl
  test/runtests.jl
  test/testMixtureLinearConditional.jl
  test/testSpecialOrthogonalMani.jl
  test/testSphereMani.jl
Labels: inference, manifolds, parametric solve, work in progress

#1299 varType in _solveLambdaNumeric and translation and broken SE2 tests
  src/NumericalCalculations.jl
  test/testSpecialEuclidean2Mani.jl
  test/testSpecialOrthogonalMani.jl
  test/testTranslationMani.jl
Labels: bug, enhancement, manifolds, test all the things, testing

#1300 FND w/ typeof(ccw)
  src/ApproxConv.jl
  src/CompareUtils.jl
  src/DispatchPackedConversions.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/GraphProductOperations.jl
  src/IncrementalInference.jl
  src/entities/GraphConstraintTypes.jl
Labels: enhancement, type stability

#1302 fix nullhypo mask bug in evalPotentialSpecific
  src/ApproxConv.jl
Labels: bug fix, inference, null hypothesis

#1301 bugfix for ProductRepr and include SE(2) test
  src/ApproxConv.jl
  src/NumericalCalculations.jl
  test/runtests.jl
  test/testSpecialEuclidean2Mani.jl
Labels: bug fix, manifolds

#1303 ccw points Any to fix mixed manifolds bug
  src/ApproxConv.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/NumericalCalculations.jl
  test/testSpecialEuclidean2Mani.jl
Labels: bug fix, manifolds, testing

#1304 assertion manifold point type, try calcZDim
  src/ApproxConv.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/SolverAPI.jl
  test/testSpecialSampler.jl
Labels: API, enhancement, types, user experience, variableType

#1297 towards passthrough 'sampling',
  Project.toml
  src/ApproxConv.jl
  src/CliqStateMachineUtils.jl
  src/CliqueStateMachine.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/Factors/EuclidDistance.jl
  src/Factors/PartialPriorPassThrough.jl
  src/GraphProductOperations.jl
  src/IncrementalInference.jl
  src/SolveTree.jl
  src/SolverUtilities.jl
  src/TreeMessageUtils.jl
  test/runtests.jl
  test/testEuclidDistance.jl
  test/testPartialPrior.jl
  test/testVariousNSolveSize.jl
  test/testpartialconstraint.jl
Labels: alternate PR, compat, factors, inference, manifolds, partials, performance, sampling

#1307 fix null and partial tests
  src/ApproxConv.jl
  test/runtests.jl
  test/testnullhypothesis.jl
  test/testpartialconstraint.jl
Labels: bug fix, deprecation, testing

#1295 fix null hypo partials (WIP)
  src/ApproxConv.jl
  test/runtests.jl
  test/testPartialNH.jl
Labels: WORK OUTSTANDING, back port, bug fix, inference, null hypothesis, partials, testing

#1308 restore testPartialNH.jl
  attic/TreeBasedInit_fetch.jl
  src/ApproxConv.jl
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/GraphProductOperations.jl
  src/IncrementalInference.jl
  src/InferDimensionUtils.jl
  test/testPartialNH.jl
Labels: bug, testing

#1309 improve API, towards infoPerCoord
  NEWS.md
  Project.toml
  examples/dev/factor_gradients.jl
  src/ApproxConv.jl
  src/CalcFactor.jl
  src/Deprecated.jl
  src/FGOSUtils.jl
  test/testSpecialOrthogonalMani.jl
Labels: API, compat, enhancement, gradients, manifolds, work in progress

#1310 Use getManifold on factors
  src/Factors/GenericFunctions.jl
  src/NumericalCalculations.jl
  test/testSpecialEuclidean2Mani.jl
Labels: enhancement, factors, standardization

#1311 Update SE2 manifold test with test_broken
  test/testSpecialEuclidean2Mani.jl
Labels: manifolds, regression, test all the things, testing

#1312 update deprecation in API from AMP v0.4.5
  src/TreeMessageUtils.jl
Labels: bug fix, deprecation, upstream

#1313 add _evalFactorTemporary, new test, and fixes
  examples/dev/factor_gradients.jl
  src/ApproxConv.jl
  src/CalcFactor.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/SolverUtilities.jl
  test/runtests.jl
  test/testGradientUtils.jl
Labels: enhancement

#1316 refactor calcFactorResidualTemporary, add _slack
  Project.toml
  examples/dev/factor_gradients.jl
  src/ApproxConv.jl
  src/CalcFactor.jl
  src/Deprecated.jl
  src/NumericalCalculations.jl
  src/SolverUtilities.jl
  test/runtests.jl
Labels: API, compat, maintenance, manifolds, refactoring, upstream

#1317 upgrade to FactorGradientsCached!
  Project.toml
  examples/dev/factor_gradients.jl
  src/ApproxConv.jl
  src/CalcFactor.jl
  src/Deprecated.jl
  src/FactorGraph.jl
  src/IncrementalInference.jl
  src/NumericalCalculations.jl
  src/SolverUtilities.jl
  src/Variables/DefaultVariables.jl
  src/entities/FactorGradients.jl
  src/services/FactorGradients.jl
  test/runtests.jl
  test/testApproxConv.jl
  test/testFactorGradients.jl
  test/testGradientUtils.jl
Labels: deprecation, enhancement, gradients, maintenance, partials, refactoring, testing

#1318 move MKD serialization downstream to IIF
  Project.toml
  src/DispatchPackedConversions.jl
  src/IncrementalInference.jl
  src/SerializationMKD.jl
  test/testMixtureLinearConditional.jl
  test/testgraphpackingconverters.jl
Labels: bug fix, manifolds, refactoring, serialization, standardization, testing, types, upstream, variableType

#1319 fix solveTree SE2
  NEWS.md
  Project.toml
  src/ApproxConv.jl
  src/FactorGraph.jl
  src/Factors/Circular.jl
  src/Factors/DefaultPrior.jl
  src/Factors/LinearRelative.jl
  src/Factors/Mixture.jl
  src/Factors/MsgLikelihoods.jl
  src/IncrementalInference.jl
  src/SolverUtilities.jl
  src/services/FactorGradients.jl
  test/testCommonConvWrapper.jl
  test/testMixtureParametric.jl
  test/testNumericRootGenericRandomized.jl
  test/testSpecialEuclidean2Mani.jl
  test/testSpecialOrthogonalMani.jl
  test/testgraphpackingconverters.jl
  test/testmultihypothesisapi.jl
Labels: manifolds

#1320 Towards infoPerCoord fix for partials
  src/ApproxConv.jl
  test/runtests.jl
  test/testPartialNH.jl
  test/testmultihypothesisapi.jl
  test/testpartialconstraint.jl
Labels: maintenance, standardization, testing

#1323 Manifold factors change to return coordinates
  src/Factors/GenericFunctions.jl
  src/NumericalCalculations.jl
Labels: manifolds

#1324 Fix approxDeconv for manifold
  src/DeconvUtils.jl
  src/NumericalCalculations.jl
Labels: bug fix, deconvolution, manifolds

#1322 test SE2 hex
  src/TreeMessageUtils.jl
  test/testDefaultDeconv.jl
  test/testSpecialEuclidean2Mani.jl
Labels: deconvolution, potential bug, test all the things, testing

#1325 fix tests on joint relatives
  test/testJointEnforcement.jl
Labels: bug fix, maintenance, testing

#1326 add calcHelix_T and testing
  NEWS.md
  src/CanonicalGraphExamples.jl
  test/testCircular.jl
Labels: enhancement, needed downstream, refactoring, testing
