Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2021-11, with the labels that each got.

#1440 update HeatmapGridDensity and testing
  src/services/HeatmapSampler.jl
  test/runtests.jl
  test/testHeatmapGridDensity.jl
Labels: testing, refactoring, API, sampling, heatmap

#1443 small text formatting enh
  src/services/HeatmapSampler.jl
Labels: enhancement, quality

#1445 v0.25.6-rc1
  Project.toml
  src/services/HeatmapSampler.jl
  test/runtests.jl
  test/testHeatmapGridDensity.jl
Labels: release

#1447 better selectFactorType
  src/DefaultNodeTypes.jl
Labels: refactoring, standardization, types, factors, variableType

#1448 v0.25.7-rc1
  Project.toml
  src/DefaultNodeTypes.jl
Labels: release

#1439 Default getSample methods for group manifolds
  src/ManifoldSampling.jl
  src/ParametricUtils.jl
Labels: enhancement, API, user experience, sampling, manifolds, factors

#1450 use common getSample method
  src/ExportAPI.jl
  src/Factors/Circular.jl
  src/Factors/EuclidDistance.jl
  src/Factors/GenericFunctions.jl
  src/Factors/LinearRelative.jl
  src/Factors/PartialPrior.jl
  src/IncrementalInference.jl
  src/ManifoldSampling.jl
  src/entities/SolverParams.jl
Labels: enhancement, refactoring, standardization, sampling

#1451 thread yield workaround via CalcFactor
  Project.toml
  src/Deprecated.jl
  src/FactorGraph.jl
  src/Factors/Circular.jl
  src/Factors/Mixture.jl
  src/NumericalCalculations.jl
  src/ParametricUtils.jl
  src/SolverUtilities.jl
  src/entities/FactorOperationalMemory.jl
  src/services/CalcFactor.jl
  test/testMultihypoAndChain.jl
Labels: enhancement, performance, upstream, compat, multithreading, types, potential bug

#1453 rm old deprecations
  src/Deprecated.jl
  src/Factors/Circular.jl
  src/Factors/EuclidDistance.jl
  src/Factors/LinearRelative.jl
  src/ManifoldSampling.jl
Labels: deprecation, maintenance

#1454 API change generateGraph_ABC, depr previous
  examples/TreeAnalysis.jl
  src/CanonicalGraphExamples.jl
  src/DeconvUtils.jl
  src/Deprecated.jl
  src/TreeDebugTools.jl
  src/services/CalcFactor.jl
  test/testAnalysisTools.jl
  test/testApproxConv.jl
  test/testBasicParametric.jl
  test/testBasicRecycling.jl
  test/testBasicTreeInit.jl
  test/testCSMMonitor.jl
  test/testCcolamdOrdering.jl
  test/testCliqSolveDbgUtils.jl
  test/testCliqueFactors.jl
  test/testDefaultDeconv.jl
  test/testExpXstroke.jl
  test/testHasPriors913.jl
  test/testInitVariableOrder.jl
  test/testJunctionTreeConstruction.jl
  test/testMultiprocess.jl
  test/testSaveLoadDFG.jl
  test/testSkipUpDown.jl
  test/testSolveSetPPE.jl
  test/testTreeFunctions.jl
  test/testTreeMessageUtils.jl
  test/testTreeSaveLoad.jl
  test/testVariousNSolveSize.jl
Labels: deprecation, API, standardization, breaking changes

#1458 depr api and comments to new gen
  src/SolverUtilities.jl
  test/testEuclidDistance.jl
  test/testJunctionTreeConstruction.jl
Labels: deprecation, maintenance

#1459 refactor manikde! and CalcFactor API
  Project.toml
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/services/CalcFactor.jl
Labels: enhancement, deprecation, refactoring, API, standardization

#1438 Bson testTreeSaveLoad for julia 1.7
  .github/workflows/ci.yml
  Project.toml
  src/IncrementalInference.jl
  src/JunctionTree.jl
  test/testTreeSaveLoad.jl
Labels: bug, deprecation, testing, serialization, upstream, maintenance, bayes junction tree, breaking changes, compat
