Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2021-02, with the labels that each got.

#1145 reduce productbelief, towards #1141
  src/GraphProductOperations.jl
  test/testpartialconstraint.jl
Labels: inference, refactoring

#1146 cleanup ParametricUtils.jl
  src/ParametricUtils.jl
Labels: maintenance, parametric solve, standardization

#1147 Return Residual in CalcFactor
  NEWS.md
  examples/ApproximateConvolution.jl
  examples/SquareRootTypes.jl
  src/CalcFactor.jl
  src/DeconvUtils.jl
  src/Factors/DefaultPrior.jl
  src/Factors/EuclidDistance.jl
  src/Factors/LinearRelative.jl
  src/Factors/MsgLikelihoods.jl
  src/Factors/Sphere1D.jl
  src/NumericalCalculations.jl
  src/ODE/DERelative.jl
  src/ParametricUtils.jl
  test/testCSMMonitor.jl
  test/testCommonConvWrapper.jl
  test/testDeadReckoningTether.jl
  test/testMultihypoFMD.jl
  test/testNumericRootGenericRandomized.jl
  test/testSpecialSampler.jl
  test/testmultihypothesisapi.jl
  test/testpartialconstraint.jl
Labels: breaking changes, factors, maintenance, parametric solve, standardization

#1148 fast-forward DFG integration tests
  .github/workflows/ci.yml
  NEWS.md
  Project.toml
  README.md
  examples/ApproximateConvolution.jl
  examples/SquareRootTypes.jl
  src/ApproxConv.jl
  src/CalcFactor.jl
  src/DeconvUtils.jl
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/Factors/DefaultPrior.jl
  src/Factors/EuclidDistance.jl
  src/Factors/LinearRelative.jl
  src/Factors/MsgLikelihoods.jl
  src/Factors/Sphere1D.jl
  src/GraphProductOperations.jl
  src/IncrementalInference.jl
  src/NumericalCalculations.jl
  src/ODE/DERelative.jl
  src/ParametricUtils.jl
  src/SolverAPI.jl
  src/SolverUtilities.jl
  src/TetherUtils.jl
  test/testBasicParametric.jl
  test/testCSMMonitor.jl
  test/testCommonConvWrapper.jl
  test/testDERelative.jl
  test/testDeadReckoningTether.jl
  test/testMultihypoFMD.jl
  test/testNumericRootGenericRandomized.jl
  test/testSpecialSampler.jl
  test/testmultihypothesisapi.jl
  test/testpartialconstraint.jl
Labels: dfg, fast-forward, testing, upstream

#1149 towards v0.21
  Project.toml
  src/CalcFactor.jl
  src/Deprecated.jl
  test/testCSMMonitor.jl
Labels: compat, maintenance

#1150 Update residual in _solveLambdaNumeric optim
  src/NumericalCalculations.jl
Labels: bug fix

#1152 update approxConvBinary getSample, import Optim
  src/ApproxConv.jl
  src/IncrementalInference.jl
  src/NumericalCalculations.jl
  src/ParametricUtils.jl
Labels: dead reckon tether, dependencies, maintenance, sampling, standardization, warnings

#1155 Improve types on CCW and CPT
  src/ApproxConv.jl
  src/CalcFactor.jl
  src/FactorGraphTypes.jl
  src/TetherUtils.jl
Labels: maintenance, performance, type stability, types

#1156 clean up and notes
  src/DispatchPackedConversions.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
Labels: maintenance

#1157 Fixes for plotCliqUpMsgs
  Project.toml
  src/Deprecated.jl
  src/Factors/MsgLikelihoods.jl
  src/TreeMessageUtils.jl
  test/runtests.jl
  test/testTreeMessageUtils.jl
Labels: bayes junction tree, bug fix, test all the things, testing, visualization

#1154 Parametric solve updates for CalcFactor
  src/Deprecated.jl
  src/ParametricUtils.jl
Labels: factors, maintenance, parametric solve

#1159 experimental inflation, #1051
  Project.toml
  src/ApproxConv.jl
  src/DispatchPackedConversions.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  test/testDERelative.jl
  test/testpartialconstraint.jl
Labels: API, bug fix, enhancement, experimental, feature request, inference, parameters, types

#1161 fast-forward dfg integration test
  Project.toml
  src/ApproxConv.jl
  src/CalcFactor.jl
  src/Deprecated.jl
  src/DispatchPackedConversions.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/Factors/MsgLikelihoods.jl
  src/IncrementalInference.jl
  src/NumericalCalculations.jl
  src/ParametricUtils.jl
  src/TetherUtils.jl
  src/TreeMessageUtils.jl
  test/runtests.jl
  test/testCSMMonitor.jl
  test/testDERelative.jl
  test/testTreeMessageUtils.jl
  test/testpartialconstraint.jl
Labels: dfg, fast-forward, testing, upstream

#1163 v0.21.1-rc1
  Project.toml
  src/ApproxConv.jl
  src/CalcFactor.jl
  src/Deprecated.jl
  src/DispatchPackedConversions.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/Factors/MsgLikelihoods.jl
  src/ParametricUtils.jl
  src/TetherUtils.jl
  src/TreeMessageUtils.jl
  test/runtests.jl
  test/testDERelative.jl
  test/testTreeMessageUtils.jl
  test/testpartialconstraint.jl
Labels: release

#1167 double direct during Gibbs
  Project.toml
  src/SolveTree.jl
  src/SolverAPI.jl
  test/testEuclidDistance.jl
Labels: enhancement, inference, maintenance

#1169 solveCliq! in isolation
  src/CliqueStateMachine.jl
  src/JunctionTree.jl
  src/ParametricUtils.jl
  src/SolverAPI.jl
  test/testEuclidDistance.jl
Labels: API, bayes junction tree, bug fix, clique state machine, design, question

#1171 Show CSMHistoryTuple bugfix
  src/JunctionTreeTypes.jl
Labels: bug fix, clique state machine, debug tools

#1173 Euclid Distance fg generator and tests
  src/CanonicalGraphExamples.jl
  test/testEuclidDistance.jl
Labels: bug, testing

#1175 ::TreeClique, Base.getindex, Base.show, ls
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  test/testTreeFunctions.jl
Labels: bayes junction tree, debug tools, enhancement, standardization

#1176 towards RoME 416, minimize testing, params.inflateCycles
  src/ApproxConv.jl
  src/BeliefTypes.jl
  src/Deprecated.jl
  src/FactorGraphTypes.jl
  src/Factors/EuclidDistance.jl
  src/IncrementalInference.jl
  src/SolveTree.jl
  src/SolverAPI.jl
  src/TreeDebugTools.jl
  test/runtests.jl
  test/testEuclidDistance.jl
Labels: enhancement, inference, needed downstream, solver params, testing

#1177 v0.21.2-rc1
  .github/workflows/CompatHelper.yml
  Project.toml
  src/ApproxConv.jl
  src/BeliefTypes.jl
  src/CanonicalGraphExamples.jl
  src/CliqueStateMachine.jl
  src/Deprecated.jl
  src/FactorGraphTypes.jl
  src/Factors/EuclidDistance.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/ParametricUtils.jl
  src/SolveTree.jl
  src/SolverAPI.jl
  src/TreeDebugTools.jl
  test/runtests.jl
  test/testEuclidDistance.jl
  test/testTreeFunctions.jl
Labels: release

#1178 fast-forward dfg integration testing
  .github/workflows/CompatHelper.yml
  Project.toml
  src/ApproxConv.jl
  src/BeliefTypes.jl
  src/CanonicalGraphExamples.jl
  src/CliqueStateMachine.jl
  src/Deprecated.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/Factors/EuclidDistance.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/JunctionTreeTypes.jl
  src/ParametricUtils.jl
  src/SolveTree.jl
  src/SolverAPI.jl
  src/TreeDebugTools.jl
  test/runtests.jl
  test/testEuclidDistance.jl
  test/testTreeFunctions.jl
Labels: dfg, fast-forward, testing, upstream

#1181 Update ci.yml
  .github/workflows/ci.yml
Labels: CI

#1180 Add tree message getters
  src/CliqueStateMachine.jl
  src/Factors/MsgLikelihoods.jl
  src/TreeMessageAccessors.jl
  test/testTreeMessageUtils.jl
Labels: bayes junction tree, bug fix, clique state machine, enhancement

#1184 add solveCliqUp! and api test
  src/IncrementalInference.jl
  src/SolverAPI.jl
  test/runtests.jl
  test/testCliqSolveDbgUtils.jl
Labels: bayes junction tree, clique state machine, debug tools, enhancement

#1158 multihypo fix and simple test
  Project.toml
  src/ApproxConv.jl
  src/CliqStateMachineUtils.jl
  src/ExplicitDiscreteMarginalizations.jl
  src/FGOSUtils.jl
  src/FactorGraphTypes.jl
  src/IncrementalInference.jl
  src/SolverUtilities.jl
  test/runtests.jl
  test/testMultihypoAndChain.jl
  test/testMultimodal1D.jl
  test/testmultihypothesisapi.jl
Labels: bug fix, dependencies, inference, manifolds, multihypothesis, potential bug, testing

#1186 add solveCliqDown!
  attic/CSMCommon_Consolidate.jl
  src/CliqueStateMachine.jl
  src/Deprecated.jl
  src/IncrementalInference.jl
  src/SolverAPI.jl
  src/TreeDebugTools.jl
  src/TreeMessageUtils.jl
  test/testCliqSolveDbgUtils.jl
  test/testEuclidDistance.jl
  test/testSolveSetPPE.jl
Labels: clique state machine, debug tools, inference, maintenance, test all the things

#1187 v0.21.3-rc1
  .github/workflows/ci.yml
  Project.toml
  README.md
  attic/CSMCommon_Consolidate.jl
  src/ApproxConv.jl
  src/CliqStateMachineUtils.jl
  src/CliqueStateMachine.jl
  src/Deprecated.jl
  src/ExplicitDiscreteMarginalizations.jl
  src/FGOSUtils.jl
  src/FactorGraphTypes.jl
  src/Factors/MsgLikelihoods.jl
  src/IncrementalInference.jl
  src/SolverAPI.jl
  src/SolverUtilities.jl
  src/TreeDebugTools.jl
  src/TreeMessageAccessors.jl
  src/TreeMessageUtils.jl
  test/runtests.jl
  test/testCliqSolveDbgUtils.jl
  test/testEuclidDistance.jl
  test/testMultihypoAndChain.jl
  test/testMultimodal1D.jl
  test/testSolveSetPPE.jl
  test/testTreeMessageUtils.jl
  test/testmultihypothesisapi.jl
Labels: release

#1188 fast-forward dfg integration testing v0.21.3
  .github/workflows/ci.yml
  Project.toml
  README.md
  attic/CSMCommon_Consolidate.jl
  src/ApproxConv.jl
  src/CliqStateMachineUtils.jl
  src/CliqueStateMachine.jl
  src/Deprecated.jl
  src/ExplicitDiscreteMarginalizations.jl
  src/FGOSUtils.jl
  src/FactorGraphTypes.jl
  src/Factors/MsgLikelihoods.jl
  src/IncrementalInference.jl
  src/SolverAPI.jl
  src/SolverUtilities.jl
  src/TreeDebugTools.jl
  src/TreeMessageAccessors.jl
  src/TreeMessageUtils.jl
  test/runtests.jl
  test/testCliqSolveDbgUtils.jl
  test/testEuclidDistance.jl
  test/testMultihypoAndChain.jl
  test/testMultimodal1D.jl
  test/testSolveSetPPE.jl
  test/testTreeMessageUtils.jl
  test/testmultihypothesisapi.jl
Labels: dfg, fast-forward, testing, upstream

#1193 Change default useMsgLikelihoods with warning
  src/FactorGraphTypes.jl
Labels: bug fix
