Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2021-08, with the labels that each got.

#1327 conv belief partials on AbstractPrior
  Project.toml
  src/ApproxConv.jl
  src/CalcFactor.jl
  src/CanonicalGraphExamples.jl
  src/Deprecated.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/Factors/Mixture.jl
  src/entities/FactorGradients.jl
  src/entities/GraphConstraintTypes.jl
  src/services/FactorGradients.jl
  test/testFactorGradients.jl
  test/testSpecialOrthogonalMani.jl
  test/testpartialconstraint.jl
Labels: inference, maintenance, partials, testing

#1328 Adding getFactorOperationalMemoryType for NoSolverParams
  src/IncrementalInference.jl
Labels: API, dfg, upstream

#1329 wip toward ipc via perturbation on relative
  src/ApproxConv.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/entities/FactorGradients.jl
  src/services/FactorGradients.jl
  test/runtests.jl
  test/testFactorGradients.jl
  test/testGradientUtils.jl
  test/testpartialconstraint.jl
Labels: enhancement, gradients, inference, partials, perturbation, testing

#1331 towards partial IPC on relative via gradients
  NEWS.md
  Project.toml
  src/ApproxConv.jl
  src/CalcFactor.jl
  src/Deprecated.jl
  src/DispatchPackedConversions.jl
  src/FactorGraph.jl
  src/Factors/GenericFunctions.jl
  src/NumericalCalculations.jl
  src/SolverUtilities.jl
  src/services/FactorGradients.jl
  test/testSaveLoadDFG.jl
  test/testSphereMani.jl
  test/testpartialconstraint.jl
Labels: enhancement, gradients, maintenance, partials, serialization

#1333 swap arg order calcFactorRe.. and _evalFactorTemp...
  src/ApproxConv.jl
  src/CalcFactor.jl
  src/Deprecated.jl
  src/FactorGraph.jl
  src/services/FactorGradients.jl
  test/testApproxConv.jl
  test/testGradientUtils.jl
  test/testpartialconstraint.jl
Labels: API, needed downstream, standardization

#1330 fast-forward dfg integration testing
  NEWS.md
  Project.toml
  README.md
  examples/dev/factor_gradients.jl
  src/ApproxConv.jl
  src/CalcFactor.jl
  src/CanonicalGraphExamples.jl
  src/DeconvUtils.jl
  src/Deprecated.jl
  src/DispatchPackedConversions.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/Factors/Circular.jl
  src/Factors/DefaultPrior.jl
  src/Factors/GenericFunctions.jl
  src/Factors/LinearRelative.jl
  src/Factors/Mixture.jl
  src/Factors/MsgLikelihoods.jl
  src/IncrementalInference.jl
  src/NumericalCalculations.jl
  src/SerializationMKD.jl
  src/SolverUtilities.jl
  src/TreeMessageUtils.jl
  src/Variables/DefaultVariables.jl
  src/entities/FactorGradients.jl
  src/entities/GraphConstraintTypes.jl
  src/services/FactorGradients.jl
  test/runtests.jl
  test/testApproxConv.jl
  test/testCircular.jl
  test/testCommonConvWrapper.jl
  test/testDefaultDeconv.jl
  test/testFactorGradients.jl
  test/testGradientUtils.jl
  test/testJointEnforcement.jl
  test/testMixtureLinearConditional.jl
  test/testMixtureParametric.jl
  test/testNumericRootGenericRandomized.jl
  test/testPartialNH.jl
  test/testSaveLoadDFG.jl
  test/testSpecialEuclidean2Mani.jl
  test/testSpecialOrthogonalMani.jl
  test/testSphereMani.jl
  test/testgraphpackingconverters.jl
  test/testmultihypothesisapi.jl
  test/testpartialconstraint.jl
Labels: dfg, fast-forward, testing, upstream

#1334 better organize factor ops memory as entities
  src/ApproxConv.jl
  src/CalcFactor.jl
  src/Deprecated.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/Factors/MsgLikelihoods.jl
  src/Factors/MsgPrior.jl
  src/HeatmapSampler.jl
  src/IncrementalInference.jl
  src/ParametricUtils.jl
  src/entities/BeliefTypes.jl
  src/entities/CliqueTypes.jl
  src/entities/FactorOperationalMemory.jl
  src/entities/JunctionTreeTypes.jl
  src/entities/OptionalDensities.jl
  src/entities/SolverParams.jl
  src/services/CalcFactor.jl
  src/services/CliqueTypes.jl
  src/services/FactorGradients.jl
  test/testFactorGradients.jl
Labels: maintenance, standardization

#1335 mv EvalFactor ApproxConv GenericMarginal
  src/Factors/GenericMarginal.jl
  src/IncrementalInference.jl
  src/services/ApproxConv.jl
  src/services/EvalFactor.jl
Labels: maintenance, refactoring, standardization

#1337 add AbstractManifoldMinimize to factor gradients
  src/services/FactorGradients.jl
Labels: bug fix, gradients

#1340 file cleanup and standarization, towards propagateBelief
  Project.toml
  src/DefaultNodeTypes.jl
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/Factors/PartialPriorPassThrough.jl
  src/GraphProductOperations.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/SolverUtilities.jl
  src/entities/AliasScalarSampling.jl
  src/entities/OptionalDensities.jl
  src/services/ApproxConv.jl
  src/services/BayesNet.jl
  src/services/EvalFactor.jl
  src/services/GraphInit.jl
  src/services/HeatmapSampler.jl
  test/testApproxConv.jl
  test/testFactorGradients.jl
  test/testPartialNH.jl
  test/testSpecialEuclidean2Mani.jl
Labels: deprecation, testing, refactoring, API, standardization, maintenance, bug fix, AliasingScalarSampler, partials

#1339 Fix identity to identity_element for Manifolds 0.6
  Project.toml
  examples/dev/factors_sandbox.jl
  src/Factors/GenericFunctions.jl
  src/Factors/Mixture.jl
  src/NumericalCalculations.jl
  src/SolverUtilities.jl
  src/Variables/DefaultVariables.jl
  src/services/EvalFactor.jl
  src/services/FactorGradients.jl
  test/testSpecialEuclidean2Mani.jl
Labels: bug fix, compat, manifolds

#1342 fix propagateBelief N, more testing, passThru fix
  Project.toml
  src/FactorGraph.jl
  src/Factors/PartialPrior.jl
  src/GraphProductOperations.jl
  src/IncrementalInference.jl
  src/services/ApproxConv.jl
  src/services/GraphInit.jl
  src/services/HeatmapSampler.jl
  test/testBasicGraphs.jl
  test/testPartialPrior.jl
  test/testSpecialEuclidean2Mani.jl
Labels: enhancement, testing, inference, maintenance, bug fix, compat, sampling

#1343 consolidate solveFactorParametric, and deprs
  NEWS.md
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/IncrementalInference.jl
  src/NumericalCalculations.jl
  src/ODE/DERelative.jl
  src/ParametricUtils.jl
  src/SolverUtilities.jl
  src/TetherUtils.jl
  src/entities/SolverParams.jl
  src/services/ApproxConv.jl
  src/services/EvalFactor.jl
  test/testDeadReckoningTether.jl
  test/testSaveLoadDFG.jl
Labels: enhancement, deprecation, refactoring, API, standardization, parametric solve, dead reckon tether, solver params, gradients

#1344 some cleanup
  src/IncrementalInference.jl
  test/priorusetest.jl
  test/testBasicGraphs.jl
Labels: deprecation, testing, maintenance

#1346 Mutating function in _solveLambdaNumeric cost
  Project.toml
  src/NumericalCalculations.jl
Labels: performance, manifolds, numerical

#1347 fix getManifolds -> getManifold
  src/services/GraphInit.jl
Labels: needs testing, bug fix

#1345 Standardize to TranslationGroup
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/Factors/EuclidDistance.jl
  src/Factors/LinearRelative.jl
  src/IncrementalInference.jl
  src/ParametricUtils.jl
  src/SolverUtilities.jl
  src/entities/OptionalDensities.jl
  src/entities/SolverParams.jl
  src/services/ApproxConv.jl
  test/testDeadReckoningTether.jl
Labels: standardization, maintenance, solver params, work in progress

#1349 fix solveFactorParametric as coordinates only
  src/TetherUtils.jl
  src/services/ApproxConv.jl
  test/testDeadReckoningTether.jl
Labels: API, design, standardization, parametric solve, dead reckon tether, types, sampling, manifolds

#1350 more cleanup, rm getManifolds
  .github/workflows/ci.yml
  src/FactorGraph.jl
  src/ParametricUtils.jl
  src/TreeMessageUtils.jl
  src/Variables/DefaultVariables.jl
Labels: maintenance

#1352 comments for future work
  src/SolverUtilities.jl
  src/services/ApproxConv.jl
Labels: deprecation, feature request, refactoring, graph management, work in progress

#1354 change to hyporecipe and better names
  src/DeconvUtils.jl
  src/ExplicitDiscreteMarginalizations.jl
  src/NumericalCalculations.jl
  src/services/ApproxConv.jl
  src/services/EvalFactor.jl
  test/testExplicitMultihypo.jl
Labels: multihypothesis, standardization, quality

#1356 fix calcVariableDistanceExpectedFractional
  src/NumericalCalculations.jl
  src/services/EvalFactor.jl
  test/testSpecialEuclidean2Mani.jl
  test/testTranslationMani.jl
Labels: testing, needs testing, bug fix, manifolds, test all the things

#1359 `sampleTangent` and `samplePoint`
  src/Factors/GenericFunctions.jl
  src/IncrementalInference.jl
  src/ManifoldSampling.jl
  test/testSpecialEuclidean2Mani.jl
  test/testSphereMani.jl
Labels: API, sampling, manifolds

#1360 Merge sampleTangent and samplePoint to master
  src/Factors/GenericFunctions.jl
  src/IncrementalInference.jl
  src/ManifoldSampling.jl
  test/testSpecialEuclidean2Mani.jl
  test/testSphereMani.jl
Labels: sampling, manifolds

#1361 Remove N-number of samples from `getSample` and change to `Vector{T}`
  NEWS.md
  src/ConsolidateParametricRelatives.jl
  src/DeconvUtils.jl
  src/Deprecated.jl
  src/FactorGraph.jl
  src/Factors/Circular.jl
  src/Factors/DefaultPrior.jl
  src/Factors/EuclidDistance.jl
  src/Factors/GenericFunctions.jl
  src/Factors/GenericMarginal.jl
  src/Factors/LinearRelative.jl
  src/Factors/Mixture.jl
  src/Factors/MsgPrior.jl
  src/Factors/PartialPrior.jl
  src/Factors/PartialPriorPassThrough.jl
  src/IncrementalInference.jl
  src/ManifoldSampling.jl
  src/NumericalCalculations.jl
  src/ODE/DERelative.jl
  src/SolverUtilities.jl
  src/entities/FactorGradients.jl
  src/entities/FactorOperationalMemory.jl
  src/entities/GraphConstraintTypes.jl
  src/services/ApproxConv.jl
  src/services/CalcFactor.jl
  src/services/EvalFactor.jl
  src/services/FactorGradients.jl
  test/runtests.jl
  test/testApproxConv.jl
  test/testCSMMonitor.jl
  test/testCommonConvWrapper.jl
  test/testDERelative.jl
  test/testDeadReckoningTether.jl
  test/testFactorGradients.jl
  test/testGradientUtils.jl
  test/testMultihypoFMD.jl
  test/testMultithreaded.jl
  test/testNLsolve.jl
  test/testNumericRootGenericRandomized.jl
  test/testPartialNH.jl
  test/testPartialPrior.jl
  test/testSolveKey.jl
  test/testSpecialEuclidean2Mani.jl
  test/testSpecialOrthogonalMani.jl
  test/testSpecialSampler.jl
  test/testmultihypothesisapi.jl
  test/testpartialconstraint.jl
Labels: standardization, maintenance, breaking changes, user experience, sampling

#1358 refactor hyporecipe
  src/GraphProductOperations.jl
  src/NumericalCalculations.jl
  src/services/EvalFactor.jl
  src/services/FactorGradients.jl
  test/runtests.jl
Labels: enhancement, refactoring, multihypothesis, WORK OUTSTANDING

#1362 ccw.params is now a NamedTuple
  Project.toml
  src/CompareUtils.jl
  src/FactorGraph.jl
  src/Factors/GenericFunctions.jl
  src/GraphProductOperations.jl
  src/NumericalCalculations.jl
  src/ODE/DERelative.jl
  src/entities/FactorOperationalMemory.jl
  src/services/CalcFactor.jl
  test/runtests.jl
  test/testMixtureLinearConditional.jl
  test/testSpecialEuclidean2Mani.jl
Labels: enhancement, performance, inference, types, type stability

#1366 update API getPointPartial!
  Project.toml
  src/services/EvalFactor.jl
Labels: deprecation, API, standardization, upstream, maintenance

#1367 update heatmap sampler for new API tangents
  src/Factors/PartialPriorPassThrough.jl
  src/entities/OptionalDensities.jl
Labels: API, standardization, maintenance, needs testing, sampling

#1368 Try getManifold fall back to getManifoldPartial to get the manifold used in partial priors
  src/services/EvalFactor.jl
  test/testPartialPrior.jl
  test/testSpecialEuclidean2Mani.jl
Labels: manifolds, partials
