Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2021-09, with the labels that each got.

#1375 remove ccw.specialzDim
  src/FactorGraph.jl
  src/entities/FactorOperationalMemory.jl
  src/services/CalcFactor.jl
  src/services/HeatmapSampler.jl
Labels: standardization, obsolete, maintenance, manifolds, partials

#1376 consolidate to ccw.partialDims, not cpt_.p
  src/Deprecated.jl
  src/DispatchPackedConversions.jl
  src/FactorGraph.jl
  src/NumericalCalculations.jl
  src/entities/FactorOperationalMemory.jl
  src/services/CalcFactor.jl
  src/services/EvalFactor.jl
Labels: refactoring, API, standardization, partials

#1377 depr CSMOccuranceUtils and bug fix
  attic/CSMOccuranceUtils.jl
  src/Deprecated.jl
  src/IncrementalInference.jl
  src/TreeMessageUtils.jl
Labels: deprecation, API, obsolete, maintenance, breaking changes, clique state machine, bug fix

#1378 move MsgLikelihoods services
  src/Factors/MsgLikelihoods.jl
  src/IncrementalInference.jl
  src/services/CliqueTypes.jl
Labels: enhancement, standardization, maintenance

#1380 Fix and test manifold approxDeconv
  src/DeconvUtils.jl
  src/NumericalCalculations.jl
  src/services/CalcFactor.jl
  test/testSpecialEuclidean2Mani.jl
Labels: bug fix, manifolds, deconvolution, test all the things

#1381 solveTree! only returns tree
  NEWS.md
  examples/BayesTreeIllustration.jl
  examples/FixedPointIllustrationsSquare.jl
  examples/IllustrateAutoInit.jl
  examples/MultiHypo2Door.jl
  examples/MultiHypo3Door.jl
  examples/RobotFourDoor.jl
  examples/squarefixedpoint.jl
  src/IncrementalInference.jl
  src/SolverAPI.jl
  src/TreeDebugTools.jl
  src/services/HeatmapSampler.jl
  test/TestCSMMultihypo.jl
  test/fourdoortest.jl
  test/priorusetest.jl
  test/testBasicCSM.jl
  test/testBasicGraphs.jl
  test/testBasicParametric.jl
  test/testBasicRecycling.jl
  test/testBasicTreeInit.jl
  test/testCSMMonitor.jl
  test/testCommonConvWrapper.jl
  test/testCompareVariablesFactors.jl
  test/testDeadReckoningTether.jl
  test/testDefaultDeconv.jl
  test/testEuclidDistance.jl
  test/testExpXstroke.jl
  test/testHasPriors913.jl
  test/testJointEnforcement.jl
  test/testMixtureLinearConditional.jl
  test/testMultiHypo2Door.jl
  test/testMultihypoAndChain.jl
  test/testMultimodal1D.jl
  test/testProductReproducable.jl
  test/testSkipUpDown.jl
  test/testSolveOrphanedFG.jl
  test/testSpecialEuclidean2Mani.jl
  test/testSpecialSampler.jl
  test/testTreeFunctions.jl
  test/testTreeMessageUtils.jl
  test/testVariousNSolveSize.jl
  test/testlocalconstraintexamples.jl
  test/testpartialconstraint.jl
Labels: enhancement, API, breaking changes, bug fix, missing deprecation

#1387 differential factors from deconv tangents to points
  src/DeconvUtils.jl
  src/IncrementalInference.jl
  src/TreeMessageUtils.jl
Labels: enhancement, standardization, maintenance, bug fix, manifolds

#1389 Update to RealCircularGroup
  src/Deprecated.jl
  src/Factors/Circular.jl
  src/Factors/GenericFunctions.jl
  src/IncrementalInference.jl
  src/ManifoldSampling.jl
  src/SerializationMKD.jl
  src/VariableStatistics.jl
  src/Variables/DefaultVariables.jl
  src/services/EvalFactor.jl
  test/runtests.jl
Labels: enhancement, bug fix, manifolds

#1388 simplify localProduct
  src/GraphProductOperations.jl
Labels: enhancement, refactoring, inference, maintenance

#1390 isapprox on ProductRepr
  src/CompareUtils.jl
Labels: enhancement, needed downstream, API, upstream

#1392 fix bug in _checkVarByRef
  src/SolverUtilities.jl
Labels: bug fix, parametric estimates, parametric solve, utilities, simulation

#1396 bump Julia compat to 1.5
  Project.toml
Labels: upstream, compat, julia version

#1395 better IPC on ARel partial,
  src/GraphProductOperations.jl
  src/services/ApproxConv.jl
  src/services/EvalFactor.jl
  test/testpartialconstraint.jl
Labels: enhancement, inference, partials

#1397 fsat-forward dfg integration testing IIF v0.25.0
  CITATION.bib
  Project.toml
  README.md
  src/CompareUtils.jl
  src/DeconvUtils.jl
  src/Deprecated.jl
  src/Factors/Circular.jl
  src/Factors/GenericFunctions.jl
  src/GraphProductOperations.jl
  src/IncrementalInference.jl
  src/ManifoldSampling.jl
  src/SerializationMKD.jl
  src/SolverUtilities.jl
  src/TreeMessageUtils.jl
  src/VariableStatistics.jl
  src/Variables/DefaultVariables.jl
  src/services/ApproxConv.jl
  src/services/EvalFactor.jl
  src/services/HeatmapSampler.jl
  test/runtests.jl
  test/testpartialconstraint.jl
Labels: testing, upstream, fast-forward, dfg
