Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2021-06, with the labels that each got.

#1259 add overridePPE on simulated
  src/IncrementalInference.jl
  src/SolverUtilities.jl
Labels: deprecation, enhancement

#1262 checkvar for prior
  Project.toml
  src/SolverUtilities.jl
  test/testCliqSolveDbgUtils.jl
Labels: enhancement

#1263 bug fix
  src/SolverUtilities.jl
Labels: bug fix

#1265 fast-forward integration testing
  Project.toml
  src/IncrementalInference.jl
  src/SolverUtilities.jl
  test/testCliqSolveDbgUtils.jl
Labels: dfg, fast-forward, testing, upstream

#1266 mini doc fix
  src/SolverUtilities.jl
Labels: documentation

#1264 v0.24.3-rc1
  Project.toml
  src/SolverUtilities.jl
  test/testCliqSolveDbgUtils.jl
Labels: release

#1269 upstream some functions to dfg
  NEWS.md
  Project.toml
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/IncrementalInference.jl
Labels: dfg, enhancement, maintenance, upstream

#1270 add incrSuffix(::Symbol)
  Project.toml
  src/FGOSUtils.jl
  test/testBasicGraphs.jl
Labels: enhancement, user experience

#1272 v0.24.4-rc1
  NEWS.md
  Project.toml
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/IncrementalInference.jl
  test/testBasicGraphs.jl
Labels: release

#1271 fast-forward dfg integration testing
  NEWS.md
  Project.toml
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/IncrementalInference.jl
  src/SolverUtilities.jl
  test/testBasicGraphs.jl
Labels: dfg, fast-forward, testing, upstream

#1274 mini regex improvement
  src/SolverUtilities.jl
Labels: enhancement

#1275 Move getDimension(::DFGVariable) to DFG
  src/FGOSUtils.jl
  src/Variables/Circular.jl
  src/Variables/DefaultVariables.jl
Labels: breaking changes, maintenance, upstream

#1278 update compat, bump v0.25.0
  Project.toml
Labels: compat, versioning

#1277 fast-forward dfg integration testing
  Project.toml
  src/FGOSUtils.jl
  src/SolverUtilities.jl
  src/Variables/Circular.jl
  src/Variables/DefaultVariables.jl
Labels: dfg, maintenance, testing, upstream

#1276 Sandbox optimization on manifold
  examples/dev/factors_sandbox.jl
  examples/dev/optim_sandbox.jl
  src/ParametricUtils.jl
Labels: experimental, manifolds, numerical
