Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2021-01, with the labels that each got.

#1095 _getCCW clean up and improvements
  src/AdditionalUtils.jl
  src/ApproxConv.jl
  src/DeconvUtils.jl
  src/DispatchPackedConversions.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/Factors/LinearRelative.jl
  src/GraphProductOperations.jl
  src/InferDimensionUtils.jl
  src/JunctionTree.jl
  src/NumericalCalculations.jl
  src/SolverUtilities.jl
  test/testDefaultDeconv.jl
  test/testFactorMetadata.jl
  test/testMixtureLinearConditional.jl
  test/testSpecialSampler.jl
  test/testmultihypothesisapi.jl
Labels: enhancement, refactoring, testing

#1097 deconv cleanup, more testing before CalcResidual
  src/ApproxConv.jl
  src/DeconvUtils.jl
  src/Deprecated.jl
  src/ExplicitDiscreteMarginalizations.jl
  src/FGOSUtils.jl
  src/SolverUtilities.jl
  test/testDefaultDeconv.jl
Labels: deconvolution, inference, maintenance, refactoring, testing

#1098 basic deconv cleanup before CalcFactor switch
  src/DeconvUtils.jl
  src/ExplicitDiscreteMarginalizations.jl
  src/SolverUtilities.jl
  test/testDefaultDeconv.jl
Labels: deconvolution, maintenance

#1100 first test pass on CalcFactor (LinearRelative)
  src/Factors/LinearRelative.jl
  src/Factors/Mixture.jl
  src/NumericalCalculations.jl
  test/testMixtureLinearConditional.jl
  test/testMixturePrior.jl
Labels: API, breaking changes, enhancement, experimental, inference, mixture, refactoring

#1101 towards CalcFactor and cleanup
  NEWS.md
  src/ApproxConv.jl
  src/CalcFactor.jl
  src/Deprecated.jl
  src/Factors/DefaultPrior.jl
  src/Factors/EuclidDistance.jl
  src/Factors/LinearRelative.jl
  src/Factors/Mixture.jl
  src/Factors/MsgLikelihoods.jl
  src/Factors/Sphere1D.jl
  src/IncrementalInference.jl
  src/ParametricUtils.jl
  test/testBasicParametric.jl
  test/testDefaultDeconv.jl
  test/testSphere1.jl
Labels: API, deprecation, enhancement, factors, inference, maintenance, refactoring, standardization, types

#1102 introduce `getSample(::CalcFactor, ::Int)`
  NEWS.md
  src/ApproxConv.jl
  src/CalcFactor.jl
  src/DeconvUtils.jl
  src/Deprecated.jl
  src/FactorGraph.jl
  src/Factors/DefaultPrior.jl
  src/Factors/EuclidDistance.jl
  src/Factors/LinearRelative.jl
  src/Factors/Mixture.jl
  src/Factors/Sphere1D.jl
  src/NumericalCalculations.jl
  src/SolverUtilities.jl
  test/testCommonConvWrapper.jl
  test/testHasPriors913.jl
  test/testMixtureLinearConditional.jl
  test/testMixturePrior.jl
  test/testSpecialSampler.jl
Labels: API, breaking changes, design, enhancement, factors, refactoring, sampling, standardization, testing

#1107 update DERelative on new CalcFactor API
  Project.toml
  src/CalcFactor.jl
  src/Deprecated.jl
  src/FactorGraph.jl
  src/ODE/DERelative.jl
  test/testCSMMonitor.jl
  test/testCommonConvWrapper.jl
  test/testDERelative.jl
  test/testDeadReckoningTether.jl
  test/testFactorMetadata.jl
Labels: API, factors, maintenance, standardization

#1109 update multihypo for CalcFactor
  test/testMultihypoFMD.jl
  test/testmultihypothesisapi.jl
Labels: API, enhancement, factors, sampling, standardization

#1110 remaining CalcFactor deprecations
  examples/ApproximateConvolution.jl
  examples/SquareRootTypes.jl
  src/CalcFactor.jl
  src/Deprecated.jl
  src/Factors/MsgLikelihoods.jl
  src/Factors/PartialPrior.jl
  test/testNLsolve.jl
  test/testNumericRootGenericRandomized.jl
  test/testpartialconstraint.jl
Labels: API, deprecation, factors, maintenance, sampling, standardization

#1111 rm deprecated code for v0.20
  src/Deprecated.jl
Labels: breaking changes, deprecation, maintenance, versioning

#1112 v0.20.1-rc1
  Project.toml
  examples/ApproximateConvolution.jl
  examples/SquareRootTypes.jl
  src/CalcFactor.jl
  src/Deprecated.jl
  src/FactorGraph.jl
  src/Factors/MsgLikelihoods.jl
  src/Factors/PartialPrior.jl
  src/ODE/DERelative.jl
  test/testCSMMonitor.jl
  test/testCommonConvWrapper.jl
  test/testDERelative.jl
  test/testDeadReckoningTether.jl
  test/testFactorMetadata.jl
  test/testMultihypoFMD.jl
  test/testNLsolve.jl
  test/testNumericRootGenericRandomized.jl
  test/testmultihypothesisapi.jl
  test/testpartialconstraint.jl
Labels: release

#1108 Switch to Github CI
  .github/workflows/ci.yml
Labels: automation, testing, travis

#1114 add testFactorResidualBinary
  src/CalcFactor.jl
Labels: debug tools, factors, testing

#1115 v0.20.1-rc2
  .github/workflows/ci.yml
  src/CalcFactor.jl
Labels: release

#1117 v0.20.2-rc1
  Project.toml
  src/CalcFactor.jl
  src/Deprecated.jl
  test/testApproxConv.jl
Labels: release

#1119 fast forward dfg integration tests
  .github/workflows/ci.yml
  NEWS.md
  Project.toml
  examples/ApproximateConvolution.jl
  examples/SquareRootTypes.jl
  src/AdditionalUtils.jl
  src/ApproxConv.jl
  src/CalcFactor.jl
  src/DeconvUtils.jl
  src/Deprecated.jl
  src/DispatchPackedConversions.jl
  src/ExplicitDiscreteMarginalizations.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/FactorGraphTypes.jl
  src/Factors/DefaultPrior.jl
  src/Factors/EuclidDistance.jl
  src/Factors/LinearRelative.jl
  src/Factors/Mixture.jl
  src/Factors/MsgLikelihoods.jl
  src/Factors/PartialPrior.jl
  src/Factors/Sphere1D.jl
  src/GraphProductOperations.jl
  src/IncrementalInference.jl
  src/InferDimensionUtils.jl
  src/JunctionTree.jl
  src/NumericalCalculations.jl
  src/ODE/DERelative.jl
  src/ParametricUtils.jl
  src/SolverUtilities.jl
  test/testApproxConv.jl
  test/testBasicParametric.jl
  test/testCSMMonitor.jl
  test/testCommonConvWrapper.jl
  test/testDERelative.jl
  test/testDeadReckoningTether.jl
  test/testDefaultDeconv.jl
  test/testFactorMetadata.jl
  test/testHasPriors913.jl
  test/testMixtureLinearConditional.jl
  test/testMixturePrior.jl
  test/testMultihypoFMD.jl
  test/testNLsolve.jl
  test/testNumericRootGenericRandomized.jl
  test/testSpecialSampler.jl
  test/testSphere1.jl
  test/testmultihypothesisapi.jl
  test/testpartialconstraint.jl
Labels: dfg, fast-forward, testing, upstream

#1122 _findSubgraphsFactorType use nameof
  src/TreeMessageUtils.jl
Labels: bug fix

#1125 hotfix to restore tests
  test/testDefaultDeconv.jl
Labels: julia version, maintenance, testing, upstream

#1126 consolidate to one _solveCCWNumeric!
  src/NumericalCalculations.jl
  test/testCommonConvWrapper.jl
Labels: inference, maintenance, refactoring, standardization

#1127 bug fix
  src/NumericalCalculations.jl
Labels: bug fix

#1128 fast-forward dfg integration tests
  src/ApproxConv.jl
  src/CalcFactor.jl
  src/DeconvUtils.jl
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/Factors/MsgLikelihoods.jl
  src/GraphProductOperations.jl
  src/NumericalCalculations.jl
  src/TreeMessageUtils.jl
  test/testCommonConvWrapper.jl
  test/testDefaultDeconv.jl
  test/testNumericRootGenericRandomized.jl
Labels: dfg, fast-forward, testing, upstream

#1130 v0.20.3-rc1
  Project.toml
  src/ApproxConv.jl
  src/CalcFactor.jl
  src/DeconvUtils.jl
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/Factors/MsgLikelihoods.jl
  src/GraphProductOperations.jl
  src/NumericalCalculations.jl
  src/TreeMessageUtils.jl
  test/testCommonConvWrapper.jl
  test/testDefaultDeconv.jl
  test/testNumericRootGenericRandomized.jl
Labels: release

#1132 AbstractRelativeMinimize via residual
  NEWS.md
  Project.toml
  src/Factors/EuclidDistance.jl
  src/NumericalCalculations.jl
  test/testpartialconstraint.jl
Labels: API, factors, inference, refactoring, standardization

#1129 Julia 1.6 ci.yml
  .github/workflows/ci.yml
Labels: CI

#1133 maintenance on numerical calc and dispatch
  src/ApproxConv.jl
  src/DeconvUtils.jl
  src/NumericalCalculations.jl
  src/SolverUtilities.jl
Labels: inference, maintenance, type stability

#1134 rename freshSamples -> sampleFactor
  examples/ApproximateConvolution.jl
  src/ApproxConv.jl
  src/CalcFactor.jl
  src/DeconvUtils.jl
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/FactorGraph.jl
  src/IncrementalInference.jl
  src/SolverUtilities.jl
  test/testDERelative.jl
  test/testMultihypoFMD.jl
Labels: API, maintenance, standardization

#1135 standardize numeric internals (towards #1010)
  src/ApproxConv.jl
  src/DeconvUtils.jl
  src/GraphProductOperations.jl
  src/NumericalCalculations.jl
  src/TetherUtils.jl
Labels: maintenance, refactoring, standardization

#1138 CPT.res should not force type, use ::T instead
  src/FactorGraphTypes.jl
Labels: refactoring, standardization

#1142 simplify productpartials, AMP v0.1.5
  Project.toml
  src/ApproxConv.jl
  src/Deprecated.jl
  src/GraphProductOperations.jl
Labels: compat, inference, maintenance, refactoring, standardization

#1143 depr prodmultipleonefullpartials
  src/Deprecated.jl
  src/GraphProductOperations.jl
Labels: inference, refactoring

#1140 Parametric getParametricMeasurement and CalcFactorMahalanobis
  src/FactorGraph.jl
  src/ParametricUtils.jl
  src/SolverAPI.jl
  test/testBasicParametric.jl
Labels: factors, parametric solve, refactoring
