Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2022-07, with the labels that each got.

#1550 v0.29.1rc1
  NEWS.md
  Project.toml
  src/services/GraphInit.jl
Labels: release

#1552 Change to support ArrayPartition by dafault
  .github/workflows/ci.yml
  Project.toml
  src/IncrementalInference.jl
  src/ManifoldSampling.jl
  src/ManifoldsExtentions.jl
  src/services/GraphInit.jl
  test/testSpecialEuclidean2Mani.jl
Labels: enhancement, breaking changes, manifolds

#1554 fix multihypo #424, and depr fix
  src/FactorGraph.jl
  test/testMultihypoFMD.jl
  test/testSphereMani.jl
Labels: enhancement

#1553 Slightly better _prepParamVec
  src/services/CalcFactor.jl
  test/testGradientUtils.jl
Labels: performance, bug fix, type stability, work in progress

#1555 ProductRepr fixes and maintenance
  src/ConsolidateParametricRelatives.jl
  src/services/CalcFactor.jl
  src/services/EvalFactor.jl
  src/services/GraphInit.jl
Labels: maintenance, manifolds, quality

#1557 temporary test order, 3door mh
  test/runtests.jl
Labels: regression, testing, multihypothesis

#1558 Remove deprecations and update news
  NEWS.md
  src/Deprecated.jl
  src/ExportAPI.jl
  src/FactorGraph.jl
  src/JunctionTree.jl
  src/ParametricUtils.jl
  src/SolverUtilities.jl
  src/TreeMessageUtils.jl
  src/entities/JunctionTreeTypes.jl
  src/services/ApproxConv.jl
  src/services/CalcFactor.jl
  src/services/CliqueTypes.jl
  src/services/GraphInit.jl
  test/runtests.jl
  test/testApproxConv.jl
  test/testBasicCSM.jl
  test/testCommonConvWrapper.jl
  test/testDERelative.jl
  test/testEuclidDistance.jl
  test/testJointEnforcement.jl
  test/testMixtureLinearConditional.jl
  test/testProductReproducable.jl
  test/testSolveKey.jl
  test/testgraphpackingconverters.jl
  test/testlocalconstraintexamples.jl
  test/testmultihypothesisapi.jl
Labels: deprecation, standardization, maintenance

#1560 Parametric Refactor
  Project.toml
  src/IncrementalInference.jl
  src/ManifoldsExtentions.jl
  src/ParametricUtils.jl
  src/entities/FactorOperationalMemory.jl
  src/entities/SolverParams.jl
  test/testBasicParametric.jl
  test/testMixtureParametric.jl
Labels: refactoring, performance, standardization, maintenance, parametric solve

#1565 CCW.params NamedTuple->Tuple
  src/IncrementalInference.jl
  src/NumericalCalculations.jl
  src/entities/FactorOperationalMemory.jl
  src/services/CalcFactor.jl
  src/services/EvalFactor.jl
Labels: performance, bug fix

#1569 OrderedDict changed variable ordering
  src/entities/JunctionTreeTypes.jl
  test/testBasicRecycling.jl
  test/testInitVariableOrder.jl
Labels: testing, upstream, variable ordering

#1577 workflow_dispatch in CI
  .github/workflows/ci.yml
Labels: CI

#1572 v0.30.1-rc1
  .github/workflows/ci.yml
  Project.toml
  src/Factors/GenericFunctions.jl
  src/Factors/LinearRelative.jl
  src/IncrementalInference.jl
  src/ManifoldSampling.jl
  src/ManifoldsExtentions.jl
  src/NumericalCalculations.jl
  src/ParametricUtils.jl
  src/entities/FactorOperationalMemory.jl
  src/entities/JunctionTreeTypes.jl
  src/entities/SolverParams.jl
  src/services/CalcFactor.jl
  src/services/EvalFactor.jl
  src/services/GraphInit.jl
  test/runtests.jl
  test/testBasicParametric.jl
  test/testBasicRecycling.jl
  test/testInitVariableOrder.jl
  test/testMixtureParametric.jl
  test/testSpecialEuclidean2Mani.jl
  test/testUseMsgLikelihoods.jl
Labels: release

#1579 MsgRelativeType as anonymous-concrete when able
  src/entities/CliqueTypes.jl
Labels: performance, inference, bayes junction tree, types

#1580 allow manikde! on varT and Tuple (not preferred)
  Project.toml
  src/Deprecated.jl
  src/FGOSUtils.jl
  test/basicGraphsOperations.jl
  test/testMultiHypo3Door.jl
  test/testSphereMani.jl
Labels: feature request, testing, API, needs testing

#1581 v0.30.2-rc1
  Project.toml
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/entities/CliqueTypes.jl
  test/basicGraphsOperations.jl
  test/testMultiHypo3Door.jl
  test/testSphereMani.jl
Labels: release
