Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2022-12, with the labels that each got.

#1638 fix depr warning on linear_interpolation
  src/entities/FactorOperationalMemory.jl
  src/services/HeatmapSampler.jl
Labels: deprecation, upstream, heatmap

#1641 makeSolverData!
  src/ExportAPI.jl
  src/services/GraphInit.jl
  test/testBasicGraphs.jl
Labels: enhancement, testing, manual init

#1642 enh makeSolverData (and use Optim.TrustRegion)
  src/IncrementalInference.jl
  src/ParametricUtils.jl
  src/SolverAPI.jl
  src/services/FactorGraph.jl
  src/services/GraphInit.jl
Labels: enhancement, parametric solve, manual init

#1644 oas skip grad on caching
  src/Serialization/services/DispatchPackedConversions.jl
  src/services/FactorGraph.jl
Labels: enhancement

#1645 add julia 1.9 to CI
  .github/workflows/ci.yml
Labels: CI, julia version

#1647 fix getMeasParm for more cases
  src/ParametricUtils.jl
Labels: enhancement, bug fix

#1643 Cleanup calcCovarianceBasic
  src/VariableStatistics.jl
  src/services/EvalFactor.jl
  test/testSpecialOrthogonalMani.jl
  test/testpartialconstraint.jl
Labels: deprecation, maintenance

#1650 Fix parametric test regression
  src/ParametricUtils.jl
Labels: bug fix, parametric solve, solver params

#1651 parametric with n-ary, ccw perf enh
  src/ParametricUtils.jl
  src/entities/FactorOperationalMemory.jl
Labels: enhancement, parametric solve, manifolds, type stability

#1653 release v0.31.1-rc1
  .github/workflows/ci.yml
  Project.toml
  src/ExportAPI.jl
  src/IncrementalInference.jl
  src/ODE/DERelative.jl
  src/ParametricUtils.jl
  src/Serialization/services/DispatchPackedConversions.jl
  src/SolverAPI.jl
  src/VariableStatistics.jl
  src/entities/FactorOperationalMemory.jl
  src/services/CalcFactor.jl
  src/services/EvalFactor.jl
  src/services/FactorGraph.jl
  src/services/GraphInit.jl
  src/services/HeatmapSampler.jl
  test/testBasicGraphs.jl
  test/testSpecialOrthogonalMani.jl
  test/testpartialconstraint.jl
Labels: release

#1652 Remove CF._measCount (and suppr MH test)
  src/Factors/Mixture.jl
  src/ParametricUtils.jl
  src/entities/FactorOperationalMemory.jl
  src/services/CalcFactor.jl
  src/services/NumericalCalculations.jl
  test/runtests.jl
Labels: enhancement, testing, refactoring, multihypothesis, standardization, types

#1655 rm CF._legacyMeas
  src/Factors/Mixture.jl
  src/ParametricUtils.jl
  src/entities/FactorOperationalMemory.jl
  src/services/CalcFactor.jl
  src/services/NumericalCalculations.jl
  src/services/SolverUtilities.jl
Labels: deprecation, refactoring, standardization, types

#1656 CF.fullvars is now a Tuple
  src/ParametricUtils.jl
  src/entities/FactorOperationalMemory.jl
  src/services/CalcFactor.jl
  src/services/NumericalCalculations.jl
Labels: enhancement, refactoring, performance, types

#1657 ccw make template fields of abstract types
  src/entities/FactorOperationalMemory.jl
Labels: enhancement, refactoring, performance, types

#1658 ccw refactor threadmodel and vartypes
  .github/workflows/ci.yml
  src/Deprecated.jl
  src/ExportAPI.jl
  src/IncrementalInference.jl
  src/entities/FactorOperationalMemory.jl
  src/services/CalcFactor.jl
  src/services/FGOSUtils.jl
  src/services/FactorGraph.jl
  src/services/NumericalCalculations.jl
  test/testMultithreaded.jl
Labels: enhancement, testing, refactoring, performance, standardization, breaking changes, CI, types

#1659 cleaner ccw varTypes
  src/entities/FactorOperationalMemory.jl
  src/services/DeconvUtils.jl
  src/services/EvalFactor.jl
  src/services/NumericalCalculations.jl
Labels: enhancement, refactoring, performance, types, variableType

#1660 ccw.varValsAll, towards better multihypo handling
  NEWS.md
  src/entities/FactorOperationalMemory.jl
  src/services/CalcFactor.jl
  src/services/EvalFactor.jl
  src/services/NumericalCalculations.jl
  src/services/SolverUtilities.jl
  test/testCommonConvWrapper.jl
  test/testCompareVariablesFactors.jl
  test/testMixtureLinearConditional.jl
Labels: refactoring, multihypothesis, standardization, types, code quality

#1662 add CalcFactor.manifold, all factors getManifold
  NEWS.md
  Project.toml
  src/Deprecated.jl
  src/Factors/GenericMarginal.jl
  src/Factors/Mixture.jl
  src/Factors/PartialPrior.jl
  src/Factors/PartialPriorPassThrough.jl
  src/ParametricUtils.jl
  src/entities/FactorOperationalMemory.jl
  src/services/CalcFactor.jl
  src/services/EvalFactor.jl
  src/services/NumericalCalculations.jl
  test/runtests.jl
  test/testApproxConv.jl
  test/testCSMMonitor.jl
  test/testCalcFactorHypos.jl
  test/testCommonConvWrapper.jl
  test/testPartialFactors.jl
  test/testPartialNH.jl
  test/testPartialPrior.jl
  test/testSpecialEuclidean2Mani.jl
  test/testSpecialSampler.jl
  test/testmultihypothesisapi.jl
  test/testpartialconstraint.jl
Labels: deprecation, testing, standardization, inference, breaking changes, types, factors, partials

#1663 deprs and slow getClique warnings
  attic/CliqueStateMachine_fetch.jl
  attic/examples/BayesTreeIllustration.jl
  attic/examples/MultiHypo2Door.jl
  attic/examples/MultiHypo3Door.jl
  src/AnalysisTools.jl
  src/Deprecated.jl
  src/SolverAPI.jl
  src/services/JunctionTreeUtils.jl
  src/services/TreeDebugTools.jl
  test/testAnalysisTools.jl
  test/testBasicRecycling.jl
  test/testDefaultDeconv.jl
Labels: deprecation, maintenance, bayes junction tree

#1664 faster getManifold for factor calcs (ccw.manifold)
  src/ParametricUtils.jl
  src/entities/FactorOperationalMemory.jl
  src/services/CalcFactor.jl
Labels: performance, standardization, inference, types, manifolds

#1665 switch to using ccw.manifold
  src/Factors/Circular.jl
  src/Factors/GenericFunctions.jl
  src/Factors/PartialPriorPassThrough.jl
  src/ManifoldSampling.jl
  src/services/CalcFactor.jl
  test/testSpecialEuclidean2Mani.jl
Labels: refactoring, performance, inference, types, factors

#1666 impr testing, better ccw field order towards multihypo checks
  src/entities/FactorOperationalMemory.jl
  src/services/CalcFactor.jl
  src/services/EvalFactor.jl
  src/services/NumericalCalculations.jl
  test/runtests.jl
  test/testNumericRootGenericRandomized.jl
Labels: enhancement, deprecation, testing, refactoring, inference, types, sampling, code quality

#1667 consolidate ccw.meas factor sampling
  NEWS.md
  src/services/CalcFactor.jl
  src/services/EvalFactor.jl
  src/services/FactorGradients.jl
  src/services/SolverUtilities.jl
  test/runtests.jl
  test/testMixturePrior.jl
  test/testMultiHypo3Door.jl
  test/testSpecialEuclidean2Mani.jl
Labels: enhancement, testing, refactoring, multihypothesis, standardization, sampling, factors, code quality
