Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2022-08, with the labels that each got.

#1568 solveGraphParametric returns points on manifold
  src/Deprecated.jl
  src/ManifoldsExtentions.jl
  src/ParametricCSMFunctions.jl
  src/ParametricUtils.jl
  test/testBasicParametric.jl
Labels: bug fix, parametric solve

#1586 v0.30.3-rc1
  Project.toml
  src/Deprecated.jl
  src/ManifoldsExtentions.jl
  src/ParametricCSMFunctions.jl
  src/ParametricUtils.jl
  test/testBasicParametric.jl
Labels: release

#1590 move src to services
  src/ExportAPI.jl
  src/IncrementalInference.jl
  src/entities/JunctionTreeTypes.jl
  src/services/CliqStateMachineUtils.jl
  src/services/CompareUtils.jl
  src/services/DeconvUtils.jl
  src/services/DefaultNodeTypes.jl
  src/services/ExplicitDiscreteMarginalizations.jl
  src/services/FGOSUtils.jl
  src/services/FactorGraph.jl
  src/services/GraphProductOperations.jl
  src/services/NumericalCalculations.jl
  src/services/SolveTree.jl
  src/services/SolverUtilities.jl
  src/services/SubGraphFunctions.jl
  src/services/TetherUtils.jl
  src/services/TreeBasedInitialization.jl
  src/services/TreeDebugTools.jl
  src/services/TreeMessageAccessors.jl
  src/services/TreeMessageUtils.jl
Labels: enhancement, standardization, quality

#1591 Impr docs on solveConditionalsParametric
  src/ParametricUtils.jl
Labels: documentation, standardization, quality

#1592 minor tweaks to test numerics
  test/testHeatmapGridDensity.jl
  test/testMixturePrior.jl
  test/testMultiHypo3Door.jl
  test/testPartialNH.jl
Labels: enhancement, testing

#1593 mv files to services (tree related)
  src/CliqueStateMachine/services/CliqStateMachineUtils.jl
  src/CliqueStateMachine/services/CliqueStateMachine.jl
  src/ExportAPI.jl
  src/IncrementalInference.jl
  src/entities/JunctionTreeTypes.jl
  src/services/AdditionalUtils.jl
  src/services/JunctionTree.jl
  src/services/JunctionTreeUtils.jl
Labels: refactoring, standardization, maintenance

#1596 minor test adjustment
  test/testSpecialEuclidean2Mani.jl
Labels: testing

#1597 initAll! for `:parametric`
  Project.toml
  src/ParametricUtils.jl
  src/services/GraphInit.jl
  test/testBasicParametric.jl
  test/testMultiHypo3Door.jl
Labels: enhancement, testing, autoinit, parametric solve

#1598 v0.30.4-rc1
  NEWS.md
  Project.toml
  src/CliqueStateMachine/services/CliqStateMachineUtils.jl
  src/CliqueStateMachine/services/CliqueStateMachine.jl
  src/ExportAPI.jl
  src/IncrementalInference.jl
  src/ParametricUtils.jl
  src/entities/JunctionTreeTypes.jl
  src/services/AdditionalUtils.jl
  src/services/CompareUtils.jl
  src/services/DeconvUtils.jl
  src/services/DefaultNodeTypes.jl
  src/services/ExplicitDiscreteMarginalizations.jl
  src/services/FGOSUtils.jl
  src/services/FactorGraph.jl
  src/services/GraphInit.jl
  src/services/GraphProductOperations.jl
  src/services/JunctionTree.jl
  src/services/JunctionTreeUtils.jl
  src/services/MaxMixture.jl
  src/services/NumericalCalculations.jl
  src/services/SolveTree.jl
  src/services/SolverUtilities.jl
  src/services/SubGraphFunctions.jl
  src/services/TetherUtils.jl
  src/services/TreeBasedInitialization.jl
  src/services/TreeDebugTools.jl
  src/services/TreeMessageAccessors.jl
  src/services/TreeMessageUtils.jl
  test/testBasicParametric.jl
  test/testHeatmapGridDensity.jl
  test/testMixturePrior.jl
  test/testMultiHypo3Door.jl
  test/testPartialNH.jl
  test/testSpecialEuclidean2Mani.jl
Labels: release

#1600 Update CI for julia v1.8
  .github/workflows/ci.yml
Labels: CI, julia version

#1601 Fix julia 1.8 bug on tree deepcopy
  .github/workflows/ci.yml
  src/entities/JunctionTreeTypes.jl
Labels: bug fix

#1602 v30.5 rc-1
  .github/workflows/ci.yml
  src/entities/JunctionTreeTypes.jl
Labels: release

#1604 Separate known stochastic failure as separate group
  .github/workflows/ci.yml
  test/runtests.jl
Labels: testing, multihypothesis, CI, potential bug

#1608 flip test order
  .github/workflows/ci.yml
Labels: CI

#1607 accelerate parametric PR CI
  .github/workflows/ci.yml
  test/runtests.jl
Labels: fast-forward, CI

#1594 Improve allocations of get_vector! and exp! and autoinitParametric
  Project.toml
  src/ManifoldsExtentions.jl
  src/ParametricUtils.jl
  src/services/GraphInit.jl
  src/services/MaxMixture.jl
Labels: performance, experimental, parametric solve

#1610 better add solverData fields on parametric init
  src/ParametricUtils.jl
  src/services/GraphInit.jl
Labels: enhancement, autoinit, parametric solve

#1613 v0.30.6-rc1
  .github/workflows/ci.yml
  LICENSE
  Project.toml
  src/ManifoldsExtentions.jl
  src/ParametricUtils.jl
  src/services/GraphInit.jl
  src/services/MaxMixture.jl
  src/services/TetherUtils.jl
  test/runtests.jl
Labels: release

#1611 Remove FactorMetaData
  NEWS.md
  Project.toml
  src/ExportAPI.jl
  src/Factors/Mixture.jl
  src/ODE/DERelative.jl
  src/ParametricUtils.jl
  src/entities/FactorOperationalMemory.jl
  src/services/CalcFactor.jl
  src/services/DeconvUtils.jl
  src/services/EvalFactor.jl
  src/services/NumericalCalculations.jl
  src/services/SolverUtilities.jl
  test/fourdoortest.jl
  test/runtests.jl
  test/testCompareVariablesFactors.jl
  test/testFactorMetadata.jl
  test/testMixtureLinearConditional.jl
  test/testMultihypoFMD.jl
Labels: deprecation, standardization, maintenance, breaking changes

#1617 Test Point2Point2Range as in RoME
  src/services/EvalFactor.jl
  test/testEuclidDistance.jl
Labels: testing, bug fix, back port, test all the things

#1615 Remove CPT
  src/entities/FactorOperationalMemory.jl
  src/services/CalcFactor.jl
  src/services/DeconvUtils.jl
  src/services/EvalFactor.jl
  src/services/NumericalCalculations.jl
  test/testMultithreaded.jl
Labels: maintenance, multithreading

#1618 rc v0.30.7 Backport entropy fix
  Project.toml
  src/services/EvalFactor.jl
  test/testEuclidDistance.jl
Labels: release, back port
