Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2022-02, with the labels that each got.

#1477 fix depr dfg infoPerCoord
  src/FactorGraph.jl
Labels: deprecation, maintenance

#1479 Standardise to LocalDFG in IIF
  NEWS.md
  src/CanonicalGraphExamples.jl
  src/CliqueStateMachine.jl
  src/Deprecated.jl
  src/ExportAPI.jl
  src/FactorGraph.jl
  src/IncrementalInference.jl
  src/JunctionTree.jl
  src/SolverAPI.jl
  src/SubGraphFunctions.jl
  src/TreeMessageUtils.jl
  src/services/ApproxConv.jl
  test/testBasicCSM.jl
  test/testBasicParametric.jl
  test/testBasicRecycling.jl
  test/testMixtureParametric.jl
  test/testMultihypoAndChain.jl
Labels: deprecation, API, standardization, maintenance

#1486 unchecked timeout with no error msg
  test/runtests.jl
  test/testDefaultDeconv.jl
Labels: testing, bug fix

#1488 rm depr pre v0.27
  Project.toml
  attic/examples/MultiHypo2Door.jl
  attic/examples/MultiHypo3Door.jl
  attic/examples/squarefixedpoint.jl
  src/Deprecated.jl
  src/ExportAPI.jl
  src/FactorGraph.jl
  src/IncrementalInference.jl
  src/TreeMessageUtils.jl
  test/priorusetest.jl
  test/runtests.jl
  test/testBasicForwardConvolve.jl
  test/testCommonConvWrapper.jl
  test/testEuclidDistance.jl
  test/testMixtureLinearConditional.jl
  test/testMultihypoAndChain.jl
  test/testProductReproducable.jl
  test/testpartialconstraint.jl
Labels: deprecation, maintenance, breaking changes

#1491 standardize manikde! api
  src/Deprecated.jl
  src/FGOSUtils.jl
Labels: deprecation, API, standardization, maintenance

#1493 workaround for partials, xref #1492
  src/services/EvalFactor.jl
Labels: enhancement, needed downstream, workaround, partials

#1494 Release v0.27.1-rc1
  Project.toml
  src/Deprecated.jl
  src/FGOSUtils.jl
  src/services/EvalFactor.jl
Labels: release
