Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2023-05, with the labels that each got.

#1708 Solver timing and start using BenchmarkTools
  .gitignore
  benchmark/benchmarks.jl
  benchmark/runbenchmarks.jl
  benchmark/tune.json
Labels: testing, performance

#1712 Update ci.yml for jlv1.9
  .github/workflows/ci.yml
Labels: CI

#1713 Change points to StaticArrays
  Project.toml
  src/ConsolidateParametricRelatives.jl
  src/Deprecated.jl
  src/Factors/Circular.jl
  src/ManifoldsExtentions.jl
  src/ParametricUtils.jl
  src/Variables/DefaultVariables.jl
  src/services/EvalFactor.jl
  src/services/FGOSUtils.jl
  src/services/NumericalCalculations.jl
  test/testSpecialEuclidean2Mani.jl
Labels: performance, breaking changes, work in progress

#1716 rework ccw.varValsAll memory for static arrays
  src/Deprecated.jl
  src/ExportAPI.jl
  src/Factors/LinearRelative.jl
  src/IncrementalInference.jl
  src/Serialization/services/DispatchPackedConversions.jl
  src/entities/FactorOperationalMemory.jl
  src/entities/HypoRecipe.jl
  src/services/ApproxConv.jl
  src/services/CalcFactor.jl
  src/services/DeconvUtils.jl
  src/services/EvalFactor.jl
  src/services/ExplicitDiscreteMarginalizations.jl
  src/services/FGOSUtils.jl
  src/services/FactorGraph.jl
  src/services/GraphInit.jl
  src/services/GraphProductOperations.jl
  src/services/NumericalCalculations.jl
  src/services/SolveTree.jl
  test/runtests.jl
  test/testApproxConv.jl
  test/testBasicForwardConvolve.jl
  test/testCommonConvWrapper.jl
  test/testCompareVariablesFactors.jl
  test/testDeadReckoningTether.jl
  test/testMixtureLinearConditional.jl
  test/testMultiHypo3Door.jl
  test/testPartialNH.jl
  test/testPartialPrior.jl
  test/testmultihypothesisapi.jl
  test/testpartialconstraint.jl
Labels: enhancement, refactoring, performance, inference, bug fix, merge for conflict avoidance

#1720 restore three reg tests from #1716
  src/services/CalcFactor.jl
  src/services/DeconvUtils.jl
  src/services/EvalFactor.jl
  src/services/NumericalCalculations.jl
  test/manifolds/manifolddiff.jl
  test/runtests.jl
  test/testVariousNSolveSize.jl
  test/testmultihypothesisapi.jl
  test/testpartialconstraint.jl
Labels: testing
