Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2023-10, with the labels that each got.

#1776 Fix getPointType of Position{N}
  src/Variables/DefaultVariables.jl
  src/entities/ExtFactors.jl
  src/manifolds/services/ManifoldSampling.jl
  src/manifolds/services/ManifoldsExtentions.jl
  src/parametric/services/ParametricCSMFunctions.jl
  src/services/GraphInit.jl
  src/services/GraphProductOperations.jl
  src/services/NumericalCalculations.jl
  test/runtests.jl
  test/testBasicParametric.jl
  test/testDERelative.jl
  test/testSpecialEuclidean2Mani.jl
  test/testpartialconstraint.jl
Labels: needs testing, bug fix

#1778 Refactor Parametric solve for better performance and better use of Manopt.jl
  Project.toml
  src/Factors/GenericFunctions.jl
  src/Factors/Mixture.jl
  src/Factors/MsgPrior.jl
  src/IncrementalInference.jl
  src/entities/AliasScalarSampling.jl
  src/entities/CalcFactor.jl
  src/manifolds/services/ManifoldSampling.jl
  src/manifolds/services/ManifoldsExtentions.jl
  src/parametric/services/ParametricManopt.jl
  src/parametric/services/ParametricManoptDev.jl
  src/parametric/services/ParametricUtils.jl
  src/services/CalcFactor.jl
  src/services/DeconvUtils.jl
  src/services/GraphInit.jl
  src/services/MaxMixture.jl
  src/services/NumericalCalculations.jl
  src/services/SolverUtilities.jl
  src/services/VariableStatistics.jl
  test/runtests.jl
  test/testBasicParametric.jl
  test/testSpecialEuclidean2Mani.jl
  test/testSphereMani.jl
  test/testUseMsgLikelihoods.jl
Labels: performance, parametric solve

#1782 workaround hack for #1781
  src/entities/CalcFactor.jl
Labels: workaround, hack, work in progress

#1784 Swop parametric optim for manopt and better convolution performance
  benchmark/runbenchmarks.jl
  src/Factors/Circular.jl
  src/Factors/GenericFunctions.jl
  src/manifolds/services/ManifoldSampling.jl
  src/parametric/services/ParametricCSMFunctions.jl
  src/parametric/services/ParametricManopt.jl
  src/parametric/services/ParametricUtils.jl
  src/services/CalcFactor.jl
  src/services/NumericalCalculations.jl
  src/services/VariableStatistics.jl
  test/testBasicParametric.jl
Labels: performance, standardization, breaking changes, parametric solve

#1786 Use CalcFactorNormSq as functor
  src/Factors/Mixture.jl
  src/entities/CalcFactor.jl
  src/services/CalcFactor.jl
  src/services/DeconvUtils.jl
  src/services/EvalFactor.jl
  src/services/NumericalCalculations.jl
  test/testSpecialEuclidean2Mani.jl
Labels: refactoring, memory allocation, standardization, maintenance, code quality

#1790 Restore _slack in mumerical calcs
  src/Factors/Mixture.jl
  src/entities/CalcFactor.jl
  src/services/CalcFactor.jl
  src/services/NumericalCalculations.jl
Labels: maintenance, numerical

#1721 restore 3 alternate tests from #1716
  test/runtests.jl
Labels: testing

#1795 fix cmember on AMD.jl ccolamd
  ext/IncrInfrApproxMinDegreeExt.jl
  src/services/BayesNet.jl
  test/testCcolamdOrdering.jl
Labels: standardization, upstream, maintenance, bug fix, variable ordering, compat

#1789 Deconv using CalcFactor dispatch
  src/entities/CalcFactor.jl
  src/services/DeconvUtils.jl
  src/services/NumericalCalculations.jl
  test/testSpecialEuclidean2Mani.jl
Labels: standardization, deconvolution, work in progress

#1797 fast forward dfg integration tests
  NEWS.md
  Project.toml
  benchmark/runbenchmarks.jl
  ext/IncrInfrApproxMinDegreeExt.jl
  ext/IncrInfrDiffEqFactorExt.jl
  ext/WeakDepsPrototypes.jl
  src/Factors/Circular.jl
  src/Factors/GenericFunctions.jl
  src/Factors/Mixture.jl
  src/Factors/MsgPrior.jl
  src/IncrementalInference.jl
  src/Variables/DefaultVariables.jl
  src/entities/AliasScalarSampling.jl
  src/entities/CalcFactor.jl
  src/entities/ExtFactors.jl
  src/manifolds/services/ManifoldSampling.jl
  src/manifolds/services/ManifoldsExtentions.jl
  src/parametric/services/ParametricCSMFunctions.jl
  src/parametric/services/ParametricManopt.jl
  src/parametric/services/ParametricManoptDev.jl
  src/parametric/services/ParametricUtils.jl
  src/services/ApproxConv.jl
  src/services/BayesNet.jl
  src/services/CalcFactor.jl
  src/services/DeconvUtils.jl
  src/services/EvalFactor.jl
  src/services/FactorGradients.jl
  src/services/FactorGraph.jl
  src/services/GraphInit.jl
  src/services/GraphProductOperations.jl
  src/services/JunctionTreeUtils.jl
  src/services/MaxMixture.jl
  src/services/NumericalCalculations.jl
  src/services/SolveTree.jl
  src/services/SolverUtilities.jl
  src/services/VariableStatistics.jl
  test/runtests.jl
  test/testBasicGraphs.jl
  test/testBasicParametric.jl
  test/testCcolamdOrdering.jl
  test/testDERelative.jl
  test/testSpecialEuclidean2Mani.jl
  test/testSpecialOrthogonalMani.jl
  test/testSphereMani.jl
  test/testUseMsgLikelihoods.jl
  test/testpartialconstraint.jl
Labels: testing, upstream, fast-forward

#1793 rm getprop on cf.manifold
  src/entities/CalcFactor.jl
Labels: refactoring, performance, design, manifolds

#1798 min compat Manopt v0.4.40 and ManifoldsBase v0.15 fixes
  Project.toml
  src/Deprecated.jl
  src/IncrementalInference.jl
  src/Serialization/services/SerializationMKD.jl
  src/manifolds/services/ManifoldsExtentions.jl
  src/parametric/services/ParametricUtils.jl
  src/services/CompareUtils.jl
  test/testSphereMani.jl
Labels: bug fix, compat, manifolds
