Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2023-07, with the labels that each got.

#1725 wip w partials, sampleTangent
  Project.toml
  src/Factors/GenericFunctions.jl
  src/ManifoldSampling.jl
  src/VariableStatistics.jl
  src/Variables/DefaultVariables.jl
  src/services/FGOSUtils.jl
  test/manifolds/manifolddiff.jl
  test/testBasicManifolds.jl
  test/testBasicParametric.jl
  test/testSpecialEuclidean2Mani.jl
  test/testSpecialOrthogonalMani.jl
  test/testSphereMani.jl
Labels: enhancement

#1724 Riemannian Levenberg-Marquardt for parametric solver
  NEWS.md
  Project.toml
  src/Deprecated.jl
  src/Factors/EuclidDistance.jl
  src/Factors/GenericFunctions.jl
  src/Factors/GenericMarginal.jl
  src/Factors/LinearRelative.jl
  src/IncrementalInference.jl
  src/ManifoldSampling.jl
  src/ManifoldsExtentions.jl
  src/ParametricManoptDev.jl
  src/ParametricUtils.jl
  src/VariableStatistics.jl
  src/Variables/DefaultVariables.jl
  src/services/DeconvUtils.jl
  src/services/FGOSUtils.jl
  src/services/GraphInit.jl
  src/services/NumericalCalculations.jl
  test/manifolds/manifolddiff.jl
  test/testBasicParametric.jl
  test/testSpecialEuclidean2Mani.jl
  test/testSpecialOrthogonalMani.jl
  test/testSphereMani.jl
Labels: enhancement, manifolds

#1728 better organize src files
  src/Deprecated.jl
  src/IncrementalInference.jl
  src/entities/CalcFactor.jl
  src/entities/FactorOperationalMemory.jl
  src/manifolds/services/ManifoldSampling.jl
  src/manifolds/services/ManifoldsExtentions.jl
  src/parametric/services/ConsolidateParametricRelatives.jl
  src/parametric/services/ParametricCSMFunctions.jl
  src/parametric/services/ParametricManoptDev.jl
  src/parametric/services/ParametricOptim.jl
  src/parametric/services/ParametricUtils.jl
  src/services/AnalysisTools.jl
  src/services/CanonicalGraphExamples.jl
  src/services/EmbeddedPlottingUtils.jl
  src/services/RequireInteractiveUtils.jl
  src/services/SolverAPI.jl
  src/services/VariableStatistics.jl
  src/services/ccolamd.jl
Labels: enhancement, refactoring

#1732 autodiff for manifolds, new test file
  Project.toml
  src/parametric/services/ParametricManoptDev.jl
  src/services/FactorGradients.jl
  test/manifolds/factordiff.jl
  test/runtests.jl
Labels: manifolds, autodiff

#1735 missed AbsRelRoots
  src/Deprecated.jl
  src/services/CalcFactor.jl
  src/services/FactorGradients.jl
  src/services/NumericalCalculations.jl
Labels: bug fix

#1736 ff dfg integration test fixes
  src/Deprecated.jl
  src/services/CalcFactor.jl
  src/services/FactorGradients.jl
  src/services/NumericalCalculations.jl
Labels: fast-forward

#1742 comp HypoRecipeCompute
  src/IncrementalInference.jl
  src/entities/HypoRecipe.jl
  src/services/HypoRecipe.jl
Labels: enhancement

#1743 ff == HypoRecipeCompute
  src/IncrementalInference.jl
  src/entities/HypoRecipe.jl
  src/services/HypoRecipe.jl
Labels: fast-forward

#1744 fix AbsRelRoots, InterpolationsExt
  Project.toml
  ext/HeatmapSampler.jl
  ext/InterpolationsExt.jl
  ext/WeakDepsPrototypes.jl
  src/IncrementalInference.jl
  test/runtests.jl
  test/testCSMMonitor.jl
  test/testCalcFactorHypos.jl
  test/testCommonConvWrapper.jl
  test/testCompareVariablesFactors.jl
  test/testDeadReckoningTether.jl
  test/testMixtureLinearConditional.jl
  test/testSpecialSampler.jl
  test/testmultihypothesisapi.jl
Labels: enhancement, deprecation, testing, refactoring, standardization, types, weakdeps

#1745 drop NLsolve dependency
  Project.toml
  src/IncrementalInference.jl
  src/services/NumericalCalculations.jl
  test/runtests.jl
  test/testCommonConvWrapper.jl
  test/testNLsolve.jl
Labels: testing, standardization, inference, dependencies, breaking changes

#1746 weakdeps InteractiveUtils
  Project.toml
  ext/InteractiveUtilsExt.jl
  ext/WeakDepsPrototypes.jl
  src/ExportAPI.jl
  src/IncrementalInference.jl
  test/basicGraphsOperations.jl
Labels: refactoring, standardization, weakdeps

#1747 GadflyExt (not working)
  Project.toml
  ext/GadflyExt.jl
  ext/WeakDepsPrototypes.jl
  src/Deprecated.jl
  src/ExportAPI.jl
  src/IncrementalInference.jl
  test/testBasicTreeInit.jl
Labels: refactoring, visualization, DEFERRED

#1748 wip DiffEqFactorExt
  Project.toml
  ext/DiffEqFactorExt.jl
  ext/GadflyExt.jl
  ext/WeakDepsPrototypes.jl
  src/ExportAPI.jl
  src/IncrementalInference.jl
  test/runtests.jl
Labels: enhancement, refactoring, standardization, needs testing, dependencies, factors, weakdeps

#1749 weakdeps FluxFactorsExt, drop Requires
  Project.toml
  ext/DiffEqFactorExt.jl
  ext/FluxFactorsExt.jl
  ext/FluxModelsSerialization.jl
  ext/HeatmapSampler.jl
  ext/InterpolationsExt.jl
  ext/WeakDepsPrototypes.jl
  src/Deprecated.jl
  src/ExportAPI.jl
  src/IncrementalInference.jl
  src/Serialization/entities/AdditionalDensities.jl
  src/Serialization/entities/SerializingOptionalDensities.jl
  src/Serialization/services/SerializingDistributions.jl
  src/Serialization/services/SerializingOptionalDensities.jl
  src/entities/BeliefTypes.jl
  src/entities/OptionalDensities.jl
  src/entities/OptionalDensitiesSerialization.jl
Labels: enhancement, refactoring, standardization, dependencies, factors, flux, weakdeps

#1750 fix ispartial case on AbstractPrior
  src/services/EvalFactor.jl
Labels: bug fix, partials

#1752 Support SolverParams in fileDFG and rm loadDFG
  src/entities/SolverParams.jl
  src/services/FGOSUtils.jl
Labels: enhancement, serialization, solver params

#1754 updates for DFG v0.23
  Project.toml
  src/Serialization/services/DispatchPackedConversions.jl
  src/services/BayesNet.jl
  src/services/FGOSUtils.jl
  src/services/GraphInit.jl
  src/services/GraphProductOperations.jl
  src/services/SubGraphFunctions.jl
Labels: enhancement, deprecation, compat

#1755 Ext with IncrInfr prefix
  Project.toml
  ext/IncrInfrDiffEqFactorExt.jl
  ext/IncrInfrFluxFactorsExt.jl
  ext/IncrInfrGadflyExt.jl
  ext/IncrInfrInteractiveUtilsExt.jl
  ext/IncrInfrInterpolationsExt.jl
Labels: weakdeps

#1756 fast forward dfg test
  Project.toml
  ext/IncrInfrDiffEqFactorExt.jl
  ext/IncrInfrFluxFactorsExt.jl
  ext/IncrInfrGadflyExt.jl
  ext/IncrInfrInteractiveUtilsExt.jl
  ext/IncrInfrInterpolationsExt.jl
  src/Serialization/services/DispatchPackedConversions.jl
  src/services/BayesNet.jl
  src/services/FGOSUtils.jl
  src/services/GraphInit.jl
  src/services/GraphProductOperations.jl
  src/services/SubGraphFunctions.jl
Labels: fast-forward, dfg, test all the things

#1757 type docs on SolverParams
  src/entities/SolverParams.jl
Labels: enhancement, documentation, solver params

#1761 Fix missed get->listNeighbors
  src/services/TreeBasedInitialization.jl
Labels: deprecation, standardization, maintenance

#1759 incr test cov Heatmap and LevelSet
  test/testHeatmapGridDensity.jl
  test/testSpecialEuclidean2Mani.jl
Labels: testing, heatmap
