Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2023-03, with the labels that each got.

#1686 update IIF for DFG v0.20
  Project.toml
  src/ExportAPI.jl
  src/Factors/PartialPriorPassThrough.jl
  src/IncrementalInference.jl
  src/SolverAPI.jl
  src/entities/BeliefTypes.jl
  test/testFluxModelsDistribution.jl
  test/testSpecialEuclidean2Mani.jl
Labels: deprecation, upstream, maintenance, dependencies, dfg, compat

#1688 Only reconstruct gradients if attemptGradients
  src/Serialization/services/DispatchPackedConversions.jl
Labels: enhancement, gradients

#1689 Upgrades to drop JSON3 dependancy in DFG
  Project.toml
  src/IncrementalInference.jl
  src/Serialization/services/SerializingDistributions.jl
Labels: serialization, maintenance

#1690 tests not broken w dfg 20
  Project.toml
  test/testCompareVariablesFactors.jl
Labels: testing, bug fix

#1693 drop JSON1 and 2
  Project.toml
  src/Deprecated.jl
  src/IncrementalInference.jl
  src/Serialization/services/DispatchPackedConversions.jl
  src/Serialization/services/SerializationMKD.jl
  src/Serialization/services/SerializingDistributions.jl
  src/entities/FactorOperationalMemory.jl
  src/services/CalcFactor.jl
  src/services/EvalFactor.jl
  src/services/FGOSUtils.jl
  src/services/FactorGraph.jl
  test/testGradientUtils.jl
  test/testPackingMixtures.jl
  test/testSaveLoadDFG.jl
Labels: deprecation, standardization, maintenance, dependencies, compat

#1695 fast-forward dfg integration test branch
  Project.toml
  src/Deprecated.jl
  src/IncrementalInference.jl
  src/Serialization/services/DispatchPackedConversions.jl
  src/Serialization/services/SerializationMKD.jl
  src/Serialization/services/SerializingDistributions.jl
  src/entities/FactorOperationalMemory.jl
  src/services/CalcFactor.jl
  src/services/EvalFactor.jl
  src/services/FGOSUtils.jl
  src/services/FactorGraph.jl
  test/testCompareVariablesFactors.jl
  test/testGradientUtils.jl
  test/testPackingMixtures.jl
  test/testSaveLoadDFG.jl
Labels: testing, upstream, fast-forward, dfg

#1697 basic manifold diff sandbox test
  Project.toml
  src/IncrementalInference.jl
  src/ManifoldsExtentions.jl
  test/manifolds/manifolddiff.jl
  test/runtests.jl
Labels: feature request, testing, example, experimental, manifolds
