Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2024-11, with the labels that each got.

#1836 few local changes to HeatMapSampler
  ext/HeatmapSampler.jl
  src/Factors/GenericFunctions.jl
Labels: enhancement

#1846 release v0.35.5-rc1
  .github/workflows/TagBot.yml
  .github/workflows/ci.yml
  Project.toml
  ext/HeatmapSampler.jl
  src/Factors/GenericFunctions.jl
  src/Serialization/services/SerializingDistributions.jl
  src/parametric/services/ParametricManopt.jl
  src/services/FGOSUtils.jl
  src/services/FactorGraph.jl
  src/services/GraphInit.jl
  test/basicGraphsOperations.jl
  test/manifolds/factordiff.jl
  test/manifolds/manifolddiff.jl
  test/testBasicManifolds.jl
  test/testCompareVariablesFactors.jl
  test/testSpecialEuclidean2Mani.jl
Labels: release

#1850 Fix compareFactorGraphs test
  test/testCompareVariablesFactors.jl
Labels: testing, bug fix
