Repository JuliaRobotics/IncrementalInference.jl, pull requests merged in 2025-07, with the labels that each got.

#1875 Update for Abstract types from DFG 1154
  IncrementalInference/ext/FluxModelsSerialization.jl
  IncrementalInference/ext/IncrInfrDiffEqFactorExt.jl
  IncrementalInference/ext/IncrInfrInteractiveUtilsExt.jl
  IncrementalInference/src/Deprecated.jl
  IncrementalInference/src/ExportAPI.jl
  IncrementalInference/src/Factors/EuclidDistance.jl
  IncrementalInference/src/Factors/GenericFunctions.jl
  IncrementalInference/src/Factors/GenericMarginal.jl
  IncrementalInference/src/Factors/LinearRelative.jl
  IncrementalInference/src/Factors/Mixture.jl
  IncrementalInference/src/Factors/MsgPrior.jl
  IncrementalInference/src/Factors/PartialPrior.jl
  IncrementalInference/src/Factors/PartialPriorPassThrough.jl
  IncrementalInference/src/NeedsResolution.jl
  IncrementalInference/src/Serialization/entities/AdditionalDensities.jl
  IncrementalInference/src/Serialization/entities/SerializingDistributions.jl
  IncrementalInference/src/Serialization/entities/SerializingOptionalDensities.jl
  IncrementalInference/src/Serialization/services/SerializationMKD.jl
  IncrementalInference/src/Serialization/services/SerializingDistributions.jl
  IncrementalInference/src/entities/BeliefTypes.jl
  IncrementalInference/src/entities/ExtFactors.jl
  IncrementalInference/src/manifolds/services/ManifoldSampling.jl
  IncrementalInference/src/services/ApproxConv.jl
  IncrementalInference/src/services/CalcFactor.jl
  IncrementalInference/src/services/DeconvUtils.jl
  IncrementalInference/src/services/DefaultNodeTypes.jl
  IncrementalInference/src/services/EvalFactor.jl
  IncrementalInference/src/services/FGOSUtils.jl
  IncrementalInference/src/services/FactorGradients.jl
  IncrementalInference/src/services/FactorGraph.jl
  IncrementalInference/src/services/NumericalCalculations.jl
  IncrementalInference/src/services/SolverUtilities.jl
  IncrementalInference/src/services/VariableStatistics.jl
  IncrementalInference/test/basicGraphsOperations.jl
  IncrementalInference/test/testCSMMonitor.jl
  IncrementalInference/test/testCalcFactorHypos.jl
  IncrementalInference/test/testCommonConvWrapper.jl
  IncrementalInference/test/testDeadReckoningTether.jl
  IncrementalInference/test/testFluxModelsDistribution.jl
  IncrementalInference/test/testHeatmapGridDensity.jl
  IncrementalInference/test/testPackedDistributions.jl
  IncrementalInference/test/testSpecialEuclidean2Mani.jl
  IncrementalInference/test/testSpecialSampler.jl
  IncrementalInference/test/testgraphpackingconverters.jl
  IncrementalInference/test/testmultihypothesisapi.jl
  IncrementalInferenceTypes/src/factors/Circular.jl
  IncrementalInferenceTypes/src/factors/DefaultPrior.jl
  IncrementalInferenceTypes/src/factors/LinearRelative.jl
  IncrementalInferenceTypes/src/serialization/entities/SerializingDistributions.jl
  IncrementalInferenceTypes/src/variables/DefaultVariableTypes.jl
Labels: refactoring, standardization, maintenance, breaking changes, types

#1866 also test DERelative backward problem
  IncrementalInference/test/testDERelative.jl
Labels: testing, differential equations

#1878 fast-forward keep solve changes (first use is extracting DERelative odes)
  IncrementalInference/ext/IncrInfrDiffEqFactorExt.jl
  IncrementalInference/src/entities/ExtFactors.jl
  IncrementalInference/src/entities/FactorOperationalMemory.jl
  IncrementalInference/src/services/ApproxConv.jl
  IncrementalInference/src/services/CalcFactor.jl
  IncrementalInference/src/services/EvalFactor.jl
  IncrementalInference/src/services/FactorGraph.jl
  IncrementalInference/src/services/NumericalCalculations.jl
  IncrementalInference/src/services/SolverUtilities.jl
  IncrementalInference/test/testDERelative.jl
Labels: enhancement, testing, fast-forward, sampling, simulation, differential equations
